--------------------------------------------------------
--  DDL for Table AI_MODEL_PRICING
--------------------------------------------------------

  CREATE TABLE "AI8P"."AI_MODEL_PRICING" 
   (	"PROVIDER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INPUT_COST" NUMBER(10,8), 
	"OUTPUT_COST" NUMBER(10,8), 
	"UPDATED_ON" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING;
