--------------------------------------------------------
--  DDL for Table AI_RATE_LIMIT
--------------------------------------------------------

  CREATE TABLE "AI_RATE_LIMIT" 
   (	"USER_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUEST_HOUR" TIMESTAMP (0), 
	"REQUEST_COUNT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING;
