--------------------------------------------------------
--  DDL for Table APP_ENVIRONMENT
--------------------------------------------------------

  CREATE TABLE "APP_ENVIRONMENT" 
   (	"ENV_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ENV_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ENV_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APP_ID" NUMBER, 
	"CONFIG_KEY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CONFIG_VALUE" CLOB COLLATE "USING_NLS_COMP", 
	"VALUE_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'STRING', 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	"TENANT_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("CONFIG_VALUE") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
