--------------------------------------------------------
--  DDL for Table CFG_CONTEXT_INSTRUCTIONS
--------------------------------------------------------

  CREATE TABLE "AI8P"."CFG_CONTEXT_INSTRUCTIONS" 
   (	"INSTRUCTION_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTRUCTION_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"VERSION_NUMBER" NUMBER DEFAULT 1, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"GLOBAL_INSTRUCTION_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("INSTRUCTION_TEXT") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
