--------------------------------------------------------
--  DDL for Table CFG_GOVERNANCE_RULES
--------------------------------------------------------

  CREATE TABLE "AI8P"."CFG_GOVERNANCE_RULES" 
   (	"RULE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RULE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RULE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"RULE_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RULE_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"APPLIES_TO_MODES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIORITY_ORDER" NUMBER DEFAULT 100, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("RULE_TEXT") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "AI8P"."CFG_GOVERNANCE_RULES"."APPLIES_TO_MODES" IS 'Comma-separated mode codes this rule applies to (NULL = all modes)';
   COMMENT ON TABLE "AI8P"."CFG_GOVERNANCE_RULES"  IS 'Enterprise governance, safety, compliance, and ethical rules for AI behavior';
