  CREATE TABLE "CHAT_PROJECTS" 
   (	"CHAT_PROJECT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PROJECT_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"PROJECT_DESCRIPTION" CLOB, 
	"PROJECT_INSTRUCTIONS" VARCHAR2(4000), 
	"PROJECT_SUMMARY" CLOB, 
	"PROJECT_SHORT_SUMMARY" CLOB, 
	"LAST_AI_SUMMARIZED" TIMESTAMP (6), 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y', 
	"TENANT_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATED_BY" VARCHAR2(100) DEFAULT USER, 
	"OWNER_USER_ID" NUMBER, 
	"IS_DELETED" CHAR(1) DEFAULT 'N', 
	"DELETED_TS" TIMESTAMP (6), 
	"IS_DEFAULT" CHAR(1) DEFAULT 'N', 
	 CHECK (is_active IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("CHAT_PROJECT_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("PROJECT_CODE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CHAT_PROJECTS" ADD CONSTRAINT "CHAT_PROJECTS_FK2" FOREIGN KEY ("OWNER_USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;