--------------------------------------------------------
--  DDL for Table CHAT_ISSUE_ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "AI8P"."CHAT_ISSUE_ATTACHMENTS" 
   (	"ATTACHMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CHAT_ISSUE_ID" NUMBER, 
	"ATTACHMENT_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTACHMENT_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTACHMENT_SIZE" NUMBER, 
	"ATTACHMENT_BLOB" BLOB, 
	"UPLOADED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("ATTACHMENT_BLOB") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "AI8P"."CHAT_ISSUE_ATTACHMENTS"  IS 'File attachments for reported issues (screenshots, documents)';
