  CREATE TABLE "CHAT_SESSIONS" 
   (	"SESSION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SESSION_UUID" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"SESSION_TITLE" VARCHAR2(200), 
	"PROVIDER" VARCHAR2(50) DEFAULT 'OPENAI', 
	"MODEL" VARCHAR2(100), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"LAST_ACTIVITY_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y', 
	"APP_SESSION_ID" NUMBER, 
	"SESSION_METADATA" JSON, 
	"CONTEXT_DOMAIN_ID" NUMBER, 
	"TENANT_ID" NUMBER, 
	"APP_PAGE_ID" NUMBER, 
	"APP_ID" NUMBER, 
	"TOKENS_INPUT" NUMBER, 
	"TOKENS_OUTPUT" NUMBER, 
	"TOKENS_TOTAL" NUMBER, 
	"TOKENS_TOTAL_COST" NUMBER, 
	"MESSAGE_COUNT" NUMBER, 
	"CHAT_PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"IS_DELETED" CHAR(1) DEFAULT 'N', 
	"DELETED_TS" TIMESTAMP (6), 
	"PINNED_MESSAGE_IDS" VARCHAR2(4000), 
	"PRIMARY_DEPLOYMENT_ID" NUMBER, 
	"SEGMENT_ID" NUMBER, 
	"EXPERIMENT_ID" NUMBER, 
	"ASSIGNMENT_LOCKED_UNTIL" TIMESTAMP (6), 
	"TRACE_ID" VARCHAR2(200), 
	 CHECK (is_active IN ('Y', 'N')) ENABLE, 
	 PRIMARY KEY ("SESSION_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("SESSION_UUID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CHAT_SESSIONS" ADD CONSTRAINT "FK_CHAT_SESSION_PROJECT" FOREIGN KEY ("CHAT_PROJECT_ID")
	  REFERENCES "CHAT_PROJECTS" ("CHAT_PROJECT_ID") ENABLE;
  ALTER TABLE "CHAT_SESSIONS" ADD CONSTRAINT "FK_CHAT_SESS_DEPLOY" FOREIGN KEY ("PRIMARY_DEPLOYMENT_ID")
	  REFERENCES "DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ENABLE;
  ALTER TABLE "CHAT_SESSIONS" ADD CONSTRAINT "FK_CHAT_SESS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CHAT_SESSIONS" ADD CONSTRAINT "FK_CHAT_SESS_EXP" FOREIGN KEY ("EXPERIMENT_ID")
	  REFERENCES "DEPLOYMENT_EXPERIMENTS" ("EXPERIMENT_ID") ENABLE;
  ALTER TABLE "CHAT_SESSIONS" ADD CONSTRAINT "AI_CHAT_SESSIONS_FK" FOREIGN KEY ("CONTEXT_DOMAIN_ID")
	  REFERENCES "CONTEXT_DOMAINS" ("CONTEXT_DOMAIN_ID") ENABLE;

  CREATE INDEX "IDX_CHAT_SESS_SEGMENT" ON "CHAT_SESSIONS" ("SEGMENT_ID", "IS_ACTIVE") 
  ;

  CREATE INDEX "IDX_CHAT_SESS_DEPLOY" ON "CHAT_SESSIONS" ("PRIMARY_DEPLOYMENT_ID", "IS_ACTIVE") 
  ;

  CREATE INDEX "IDX_CHAT_SESSIONS_USER" ON "CHAT_SESSIONS" ("USER_ID", "LAST_ACTIVITY_DATE") 
  ;

  CREATE INDEX "IDX_CHAT_SESS_EXP" ON "CHAT_SESSIONS" ("EXPERIMENT_ID", "IS_ACTIVE") 
  ;

   COMMENT ON COLUMN "CHAT_SESSIONS"."PRIMARY_DEPLOYMENT_ID" IS 'Primary deployment version assigned to this session';
   COMMENT ON COLUMN "CHAT_SESSIONS"."SEGMENT_ID" IS 'User segment for A/B testing or canary rollout';
   COMMENT ON COLUMN "CHAT_SESSIONS"."ASSIGNMENT_LOCKED_UNTIL" IS 'Session cannot change deployments until this timestamp (sticky sessions)';
   COMMENT ON TABLE "CHAT_SESSIONS"  IS 'Chat conversation sessions with user, model, and activity tracking';