--------------------------------------------------------
--  DDL for Table CHAT_FAVORITES
--------------------------------------------------------

  CREATE TABLE "AI8P"."CHAT_FAVORITES" 
   (	"FAVORITE_ID" NUMBER DEFAULT "AI8P"."CHAT_FAVORITES_SEQ"."NEXTVAL", 
	"USER_ID" NUMBER, 
	"CHAT_MESSAGE_ID" NUMBER, 
	"CHAT_SESSION_ID" NUMBER, 
	"FAVORATE_LEVEL" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'MESSAGE', 
	"CREATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING;
