--------------------------------------------------------
--  DDL for Table CONTEXT_DOMAIN_REGISTRY
--------------------------------------------------------

  CREATE TABLE "CONTEXT_DOMAIN_REGISTRY" 
   (	"CONTEXT_DOMAIN_REGISTRY_ID" NUMBER DEFAULT "CONTEXT_DOMAIN_REGISTRY_SEQ"."NEXTVAL", 
	"CONTEXT_DOMAIN_ID" NUMBER, 
	"CONTEXT_REGISTRY_ID" NUMBER, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
