--------------------------------------------------------
--  DDL for Table CONTEXT_DOMAINS
--------------------------------------------------------

  CREATE TABLE "CONTEXT_DOMAINS" 
   (	"CONTEXT_DOMAIN_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTEXT_DOMAIN_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DOMAIN_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTEXT_DOMAIN_CATEGORY_ID" NUMBER, 
	"DETECTION_METHOD_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'MANUAL', 
	"SCOPE_TYPE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'SESSION', 
	"IS_DEFAULT" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ICON_CLASS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"HELP_TEXT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE, 
	"DOMAIN_EMBEDDING_VECTOR" VECTOR(384, FLOAT32), 
	"EMBEDDING_GENERATED_DATE" DATE, 
	"EMBEDDING_MODEL_VERSION" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"EMBEDDING_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"EMBEDDING_ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTEXT_DOMAIN_KEYWORDS" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_CONTEXT_REQUIRED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 VECTOR ("DOMAIN_EMBEDDING_VECTOR") STORE AS ( CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CONTEXT_DOMAINS"."EMBEDDING_GENERATED_DATE" IS 'Timestamp when the embedding was last generated. Used to detect outdated embeddings.';
   COMMENT ON COLUMN "CONTEXT_DOMAINS"."EMBEDDING_MODEL_VERSION" IS 'Version identifier of the embedding model used. Enables model migration tracking.';
   COMMENT ON COLUMN "CONTEXT_DOMAINS"."EMBEDDING_STATUS" IS 'Current status of embedding: PENDING (not generated), COMPLETED (ready), FAILED (generation error), OUTDATED (description changed).';
   COMMENT ON COLUMN "CONTEXT_DOMAINS"."EMBEDDING_ERROR_MESSAGE" IS 'Error details if embedding generation failed. Used for debugging and retry logic.';
