--------------------------------------------------------
--  DDL for Table CONTEXT_DOMAIN_BEHAVIORS
--------------------------------------------------------

  CREATE TABLE "CONTEXT_DOMAIN_BEHAVIORS" 
   (	"CONTEXT_DOMAIN_BEHAVIOR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTEXT_DOMAIN_ID" NUMBER, 
	"DOMAIN_BEHAVIOR_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMAT_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_DEFAULT" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON COLUMN "CONTEXT_DOMAIN_BEHAVIORS"."IS_DEFAULT" IS 'Y=This is the default behavior+format combination for this mode';
   COMMENT ON TABLE "CONTEXT_DOMAIN_BEHAVIORS"  IS 'Maps instruction modes to their default behavior profile and output format';
