--------------------------------------------------------
--  DDL for Table CONTEXT_DOMAIN_INSTRUCTIONS
--------------------------------------------------------

  CREATE TABLE "CONTEXT_DOMAIN_INSTRUCTIONS" 
   (	"CONTEXT_DOMAIN_INSTRUCTION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTEXT_DOMAIN_ID" NUMBER, 
	"INSTRUCTION_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"INSTRUCTION_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PRIMARY', 
	"INSTRUCTION_ORDER" NUMBER DEFAULT 1, 
	"CONTEXT_VARIABLES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPERATURE" NUMBER(3,2) DEFAULT 0.7, 
	"MAX_TOKENS" NUMBER, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"VERSION_NUMBER" NUMBER DEFAULT 1, 
	"EFFECTIVE_DATE" DATE DEFAULT SYSDATE, 
	"EXPIRY_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("INSTRUCTION_TEXT") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
