--------------------------------------------------------
--  DDL for Table DEBUG_CONFIG
--------------------------------------------------------

  CREATE TABLE "DEBUG_CONFIG" 
   (	"CONFIG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IS_ENABLED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"SCOPE_LEVEL" NUMBER DEFAULT 6, 
	"APP_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"SESSION_ID" NUMBER, 
	"MODULE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MIN_DEBUG_LEVEL" NUMBER DEFAULT 3, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGE_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
