   CREATE TABLE "DEBUG_LOG" 
   (	"LOG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LOG_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"DEBUG_LEVEL" NUMBER NOT NULL ENABLE, 
	"APP_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"SESSION_ID" NUMBER, 
	"SCOPE_LEVEL" VARCHAR2(30), 
	"MODULE_NAME" VARCHAR2(200), 
	"PROCEDURE_NAME" VARCHAR2(200), 
	"MESSAGE" VARCHAR2(4000), 
	"EXTRA_DATA" CLOB, 
	"TRACE_ID" VARCHAR2(200), 
	"PAGE_ID" NUMBER, 
	"LOG_TYPE" VARCHAR2(15) DEFAULT 'TECH', 
	 CONSTRAINT "DEBUG_LOG_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DEBUG_LOG" ADD CONSTRAINT "FK_DEBUG_LOG_TYPE" FOREIGN KEY ("LOG_TYPE")
	  REFERENCES "LKP_DEBUG_LOG_TYPES" ("LOG_TYPE_CODE") ENABLE;

  CREATE INDEX "DEBUG_LOG_I2" ON "DEBUG_LOG" ("APP_ID", "USER_ID", "SESSION_ID") 
  ;

  CREATE INDEX "DEBUG_LOG_I3" ON "DEBUG_LOG" ("MODULE_NAME") 
  ;

  CREATE INDEX "DEBUG_LOG_I1" ON "DEBUG_LOG" ("LOG_TS") 
  ;