--------------------------------------------------------
--  DDL for Table DEPLOYMENT_AUDIT_LOG
--------------------------------------------------------

  CREATE TABLE "DEPLOYMENT_AUDIT_LOG" 
   (	"EVENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DEPLOYMENT_ID" NUMBER, 
	"EVENT_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OLD_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEW_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_METADATA" JSON, 
	"TRIGGERED_BY_USER_ID" NUMBER, 
	"TRIGGERED_BY_SYSTEM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
 JSON ("EVENT_METADATA") STORE AS ( CHUNK 8192 RETENTION MIN 1800) ;

   COMMENT ON COLUMN "DEPLOYMENT_AUDIT_LOG"."EVENT_TYPE" IS 'Type of event: CREATED, ACTIVATED, PAUSED, PROMOTED, ROLLOUT_INCREASED, etc.';
   COMMENT ON TABLE "DEPLOYMENT_AUDIT_LOG"  IS 'Complete audit trail of deployment lifecycle events and configuration changes';
