--------------------------------------------------------
--  DDL for Table DEPLOYMENT_METRICS
--------------------------------------------------------

  CREATE TABLE "DEPLOYMENT_METRICS" 
   (	"METRIC_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DEPLOYMENT_ID" NUMBER, 
	"SEGMENT_ID" NUMBER, 
	"EXPERIMENT_ID" NUMBER, 
	"METRIC_DATE" DATE DEFAULT TRUNC(SYSDATE), 
	"METRIC_HOUR" NUMBER(2,0), 
	"TOTAL_CALLS" NUMBER DEFAULT 0, 
	"SUCCESSFUL_CALLS" NUMBER DEFAULT 0, 
	"FAILED_CALLS" NUMBER DEFAULT 0, 
	"BLOCKED_CALLS" NUMBER DEFAULT 0, 
	"REFUSAL_CALLS" NUMBER DEFAULT 0, 
	"AVG_TOTAL_PIPELINE_MS" NUMBER, 
	"P50_TOTAL_PIPELINE_MS" NUMBER, 
	"P95_TOTAL_PIPELINE_MS" NUMBER, 
	"P99_TOTAL_PIPELINE_MS" NUMBER, 
	"MAX_TOTAL_PIPELINE_MS" NUMBER, 
	"AVG_LLM_CALL_MS" NUMBER, 
	"AVG_RAG_MS" NUMBER, 
	"AVG_GOVERNANCE_MS" NUMBER, 
	"TOTAL_TOKENS_INPUT" NUMBER DEFAULT 0, 
	"TOTAL_TOKENS_OUTPUT" NUMBER DEFAULT 0, 
	"TOTAL_TOKENS" NUMBER DEFAULT 0, 
	"AVG_TOKENS_PER_CALL" NUMBER, 
	"TOTAL_COST_USD" NUMBER(12,6) DEFAULT 0, 
	"AVG_COST_PER_CALL" NUMBER(12,6), 
	"TOTAL_RATINGS" NUMBER DEFAULT 0, 
	"POSITIVE_RATINGS" NUMBER DEFAULT 0, 
	"NEGATIVE_RATINGS" NUMBER DEFAULT 0, 
	"NEUTRAL_RATINGS" NUMBER DEFAULT 0, 
	"EXCELLENT_RATINGS" NUMBER DEFAULT 0, 
	"AVG_RATING_SCORE" NUMBER, 
	"SAFETY_BLOCKS" NUMBER DEFAULT 0, 
	"TRUNCATIONS" NUMBER DEFAULT 0, 
	"UNIQUE_USERS" NUMBER DEFAULT 0, 
	"NEW_USERS" NUMBER DEFAULT 0, 
	"RETURNING_USERS" NUMBER DEFAULT 0, 
	"AVG_RAG_DOC_COUNT" NUMBER, 
	"RAG_ENABLED_CALLS" NUMBER DEFAULT 0, 
	"CALCULATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING;

   COMMENT ON COLUMN "DEPLOYMENT_METRICS"."METRIC_HOUR" IS 'Hour of day (0-23) for hourly granularity, NULL for daily rollup';
   COMMENT ON TABLE "DEPLOYMENT_METRICS"  IS 'Aggregated time-series metrics for deployment comparison and analysis';
