--------------------------------------------------------
--  DDL for Table DEPLOYMENT_VERSIONS
--------------------------------------------------------

  CREATE TABLE "DEPLOYMENT_VERSIONS" 
   (	"DEPLOYMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DEPLOYMENT_UUID" VARCHAR2(36 BYTE) COLLATE "USING_NLS_COMP" DEFAULT SYS_GUID(), 
	"DEPLOYMENT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPLOYMENT_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPLOYMENT_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'DRAFT', 
	"PROVIDER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPLOYMENT_CONFIG" JSON, 
	"ROLLOUT_PERCENTAGE" NUMBER(5,2) DEFAULT 0, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"PRIORITY" NUMBER DEFAULT 100, 
	"TARGET_SEGMENT_IDS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EXCLUDED_USER_IDS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SHADOW_PARENT_DEPLOYMENT_ID" NUMBER, 
	"SHADOW_EXECUTION_MODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ASYNC', 
	"EXPERIMENT_ID" NUMBER, 
	"VARIANT_LABEL" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CANARY_SCHEDULE_JSON" JSON, 
	"CANARY_CURRENT_STAGE" NUMBER DEFAULT 1, 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" NUMBER, 
	"UPDATED_AT" TIMESTAMP (6), 
	"ACTIVATED_AT" TIMESTAMP (6), 
	"DEACTIVATED_AT" TIMESTAMP (6), 
	"PROMOTED_AT" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
 JSON ("DEPLOYMENT_CONFIG") STORE AS ( CHUNK 8192 RETENTION MIN 1800) 
 JSON ("CANARY_SCHEDULE_JSON") STORE AS ( CHUNK 8192 RETENTION MIN 1800) ;

   COMMENT ON COLUMN "DEPLOYMENT_VERSIONS"."DEPLOYMENT_TYPE" IS 'Type: PRODUCTION, SHADOW, CANARY, AB_TEST, DRAFT';
   COMMENT ON COLUMN "DEPLOYMENT_VERSIONS"."ROLLOUT_PERCENTAGE" IS 'For CANARY: percentage of users receiving this deployment (0-100)';
   COMMENT ON COLUMN "DEPLOYMENT_VERSIONS"."TARGET_SEGMENT_IDS" IS 'Comma-separated list of USER_SEGMENTS.segment_id values';
   COMMENT ON COLUMN "DEPLOYMENT_VERSIONS"."SHADOW_EXECUTION_MODE" IS 'SYNC: blocks until complete, ASYNC: fire-and-forget, SCHEDULED: batch';
   COMMENT ON COLUMN "DEPLOYMENT_VERSIONS"."VARIANT_LABEL" IS 'For A/B tests: A, B, C, or CONTROL';
   COMMENT ON TABLE "DEPLOYMENT_VERSIONS"  IS 'Master registry for Production, Shadow, A/B Test, and Canary deployment versions';
