--------------------------------------------------------
--  DDL for Table DOC_CHUNKS
--------------------------------------------------------

  CREATE TABLE "AI8P"."DOC_CHUNKS" 
   (	"DOC_CHUNK_ID" NUMBER, 
	"DOC_ID" NUMBER, 
	"CHUNK_SEQUENCE" NUMBER, 
	"CHUNK_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"CHUNK_SIZE" NUMBER, 
	"START_POSITION" NUMBER, 
	"END_POSITION" NUMBER, 
	"CHUNKING_STRATEGY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"METADATA_JSON" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CHUNK_TOKEN_COUNT" NUMBER, 
	"EMBEDDING_ID" NUMBER, 
	"EMBEDDING_MODEL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'E5_MULTILINGUAL', 
	"EMBEDDING_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"EMBEDDING_VECTOR" VECTOR(384, FLOAT32)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("CHUNK_TEXT") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("METADATA_JSON") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 VECTOR ("EMBEDDING_VECTOR") STORE AS ( CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "AI8P"."DOC_CHUNKS"  IS 'Stores text chunks split from documents for RAG processing';
