--------------------------------------------------------
--  DDL for Table DOCS_STAGING
--------------------------------------------------------

  CREATE TABLE "AI8P"."DOCS_STAGING" 
   (	"STAGING_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DOC_ID" NUMBER, 
	"STAGE_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TEXT_ORIGINAL" CLOB COLLATE "USING_NLS_COMP", 
	"TEXT_PROPOSED" CLOB COLLATE "USING_NLS_COMP", 
	"CHANGES_JSON" JSON, 
	"ISSUES_DETECTED" JSON, 
	"QA_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"QA_DECISION_JSON" JSON, 
	"REVIEWED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEWED_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
 LOB ("TEXT_ORIGINAL") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("TEXT_PROPOSED") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 JSON ("CHANGES_JSON") STORE AS ( CHUNK 8192 RETENTION MIN 1800) 
 JSON ("ISSUES_DETECTED") STORE AS ( CHUNK 8192 RETENTION MIN 1800) 
 JSON ("QA_DECISION_JSON") STORE AS ( CHUNK 8192 RETENTION MIN 1800) ;
