--------------------------------------------------------
--  DDL for Table LKP_ERROR_SEVERITY
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_ERROR_SEVERITY" 
   (	"SEVERITY_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SEVERITY_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEVERITY_LEVEL" NUMBER, 
	"SEVERITY_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"COLOR_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON_CLASS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUIRES_ALERT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ALERT_RECIPIENTS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER, 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6), 
	"UNICODE_ICON" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON COLUMN "AI8P"."LKP_ERROR_SEVERITY"."SEVERITY_LEVEL" IS 'Numeric level: 1=LOW, 2=MEDIUM, 3=HIGH, 4=CRITICAL';
   COMMENT ON COLUMN "AI8P"."LKP_ERROR_SEVERITY"."REQUIRES_ALERT" IS 'Y=Send alert immediately, N=No immediate alert';
   COMMENT ON TABLE "AI8P"."LKP_ERROR_SEVERITY"  IS 'Standardized error severity levels with alerting configuration';
