--------------------------------------------------------
--  DDL for Table LKP_LANGUAGE_CODE
--------------------------------------------------------

  CREATE TABLE "LKP_LANGUAGE_CODE" 
   (	"LANGUAGE_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ISO_639_1" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"ISO_639_2" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCALE_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TIMEZONE_CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"UNICODE_ICON" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIVE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
