--------------------------------------------------------
--  DDL for Table LKP_PARAM_CATEGORY
--------------------------------------------------------

  CREATE TABLE "LKP_PARAM_CATEGORY" 
   (	"CATEGORY_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER DEFAULT 100, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
