--------------------------------------------------------
--  DDL for Table LKP_DEBUG_AUDIT_EVENTS
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_DEBUG_AUDIT_EVENTS" 
   (	"EVENT_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_TYPE_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_GROUP" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON_HEX" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"UI_COLOR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
