--------------------------------------------------------
--  DDL for Table LKP_INTENT_ACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "LKP_INTENT_ACTION_TYPE" 
   (	"ACTION_TYPE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTION_TYPE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTION_DESCRIPTION" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
