--------------------------------------------------------
--  DDL for Table LKP_TEST_CATEGORY
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_TEST_CATEGORY" 
   (	"CATEGORY_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER, 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
