--------------------------------------------------------
--  DDL for Table LKP_ERROR_TYPE
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_ERROR_TYPE" 
   (	"ERROR_TYPE_CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_TYPE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEVERITY_DEFAULT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_RETRYABLE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"MAX_RETRY_COUNT" NUMBER, 
	"ALERT_THRESHOLD" NUMBER, 
	"TROUBLESHOOTING_URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON COLUMN "AI8P"."LKP_ERROR_TYPE"."IS_RETRYABLE" IS 'Y=Automatic retry allowed, N=Manual intervention required';
   COMMENT ON COLUMN "AI8P"."LKP_ERROR_TYPE"."ALERT_THRESHOLD" IS 'Alert after N occurrences within 1 hour';
   COMMENT ON TABLE "AI8P"."LKP_ERROR_TYPE"  IS 'Standardized error types with retry and alerting metadata';
