--------------------------------------------------------
--  DDL for Table LKP_ROLE_CLEARANCE_LEVELS
--------------------------------------------------------

  CREATE TABLE "LKP_ROLE_CLEARANCE_LEVELS" 
   (	"CLEARANCE_LEVEL" NUMBER, 
	"CLEARANCE_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CLEARANCE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"UPDATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON_CSS_CLASS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"UNICODE_ICON" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON COLUMN "LKP_ROLE_CLEARANCE_LEVELS"."CLEARANCE_LEVEL" IS 'Numeric clearance tier: 1=Low, 2=Medium, 3=High, 4=Maximum.';
   COMMENT ON COLUMN "LKP_ROLE_CLEARANCE_LEVELS"."CLEARANCE_CODE" IS 'Neutral code representing the clearance tier (LEVEL1–LEVEL4).';
   COMMENT ON COLUMN "LKP_ROLE_CLEARANCE_LEVELS"."CLEARANCE_NAME" IS 'Human-readable name for the clearance tier.';
   COMMENT ON TABLE "LKP_ROLE_CLEARANCE_LEVELS"  IS 'Abstract clearance tiers (1–4). Not role-specific. Roles reference these levels.';
