--------------------------------------------------------
--  DDL for Table LKP_OUTPUT_FORMAT
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_OUTPUT_FORMAT" 
   (	"FORMAT_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMAT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMAT_DESCRIPTION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTRUCTION_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"EXAMPLE_OUTPUT" CLOB COLLATE "USING_NLS_COMP", 
	"APPLIES_TO_PROVIDERS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ALL', 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"DISPLAY_ORDER" NUMBER DEFAULT 100, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("INSTRUCTION_TEXT") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EXAMPLE_OUTPUT") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "AI8P"."LKP_OUTPUT_FORMAT"."INSTRUCTION_TEXT" IS 'Instructions for LLM on how to structure the output';
   COMMENT ON COLUMN "AI8P"."LKP_OUTPUT_FORMAT"."EXAMPLE_OUTPUT" IS 'Sample output demonstrating the format (optional)';
   COMMENT ON TABLE "AI8P"."LKP_OUTPUT_FORMAT"  IS 'Defines structured output formats for AI responses (JSON, Table, Summary, etc.)';
