--------------------------------------------------------
--  DDL for Table LKP_CONTEXT_REGISTRY_SOURCE_TYPES
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_CONTEXT_REGISTRY_SOURCE_TYPES" 
   (	"CONTEXT_REGISTRY_SOURCE_TYPE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"DISPLAY_ORDER" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"DESCRIPTION" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"UNICODE_ICON" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
