--------------------------------------------------------
--  DDL for Table LKP_ISSUE_TYPES
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_ISSUE_TYPES" 
   (	"ISSUE_TYPE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ISSUE_TYPE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ISSUE_TYPE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ISSUE_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEVERITY_DEFAULT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'MEDIUM', 
	"DISPLAY_ORDER" NUMBER DEFAULT 999, 
	"ICON_CLASS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON TABLE "AI8P"."LKP_ISSUE_TYPES"  IS 'Predefined issue types for LLM responses';
