--------------------------------------------------------
--  DDL for Table LKP_SEARCH_TYPE
--------------------------------------------------------

  CREATE TABLE "LKP_SEARCH_TYPE" 
   (	"SEARCH_TYPE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_TYPE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USES_EMBEDDINGS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"USES_KEYWORDS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"TYPICAL_LATENCY_MS" NUMBER, 
	"QUALITY_SCORE" NUMBER, 
	"DISPLAY_ORDER" NUMBER, 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON TABLE "LKP_SEARCH_TYPE"  IS 'Valid RAG search types with performance metadata';
