--------------------------------------------------------
--  DDL for Table LKP_REGISTERED_HANDLERS
--------------------------------------------------------

  CREATE TABLE "LKP_REGISTERED_HANDLERS" 
   (	"HANDLER_PACKAGE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_STREAM_CAPABLE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
