--------------------------------------------------------
--  DDL for Table LKP_CHUNKING_STRATEGY
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_CHUNKING_STRATEGY" 
   (	"STRATEGY_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"STRATEGY_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STRATEGY_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PACKAGE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'RAG_CHUNK_PKG', 
	"FUNCTION_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEFAULT_CHUNK_SIZE" NUMBER DEFAULT 512, 
	"DEFAULT_OVERLAP_PCT" NUMBER DEFAULT 20, 
	"DEFAULT_MAX_CHUNK_SIZE" NUMBER DEFAULT 2048, 
	"DEFAULT_MIN_CHUNK_SIZE" NUMBER DEFAULT 50, 
	"STRATEGY_PARAMETERS" JSON, 
	"RELATIVE_SPEED" NUMBER DEFAULT 1.0, 
	"STORAGE_OVERHEAD" NUMBER DEFAULT 1.0, 
	"PROCESSING_COMPLEXITY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'MEDIUM', 
	"BEST_FOR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROS" CLOB COLLATE "USING_NLS_COMP", 
	"CONS" CLOB COLLATE "USING_NLS_COMP", 
	"USE_CASES" CLOB COLLATE "USING_NLS_COMP", 
	"RECOMMENDED_DOC_TYPES" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"RECOMMENDED_SIZE_MIN" NUMBER, 
	"RECOMMENDED_SIZE_MAX" NUMBER, 
	"SEMANTIC_PRESERVATION" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'MEDIUM', 
	"BOUNDARY_ACCURACY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'MEDIUM', 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"IS_DEFAULT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"DISPLAY_ORDER" NUMBER DEFAULT 0, 
	"SUPPORTS_MULTILINGUAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"LANGUAGE_CODES" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_AT" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 JSON ("STRATEGY_PARAMETERS") STORE AS ( CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PROS") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CONS") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("USE_CASES") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "AI8P"."LKP_CHUNKING_STRATEGY"."STRATEGY_CODE" IS 'Unique code for chunking strategy (e.g., FIXED_SIZE, SENTENCE_BOUNDARY)';
   COMMENT ON COLUMN "AI8P"."LKP_CHUNKING_STRATEGY"."FUNCTION_NAME" IS 'PL/SQL function name in package that implements this strategy';
   COMMENT ON COLUMN "AI8P"."LKP_CHUNKING_STRATEGY"."STRATEGY_PARAMETERS" IS 'Additional JSON parameters for advanced configuration';
   COMMENT ON COLUMN "AI8P"."LKP_CHUNKING_STRATEGY"."RELATIVE_SPEED" IS 'Processing speed relative to fixed-size (baseline = 1.0)';
   COMMENT ON COLUMN "AI8P"."LKP_CHUNKING_STRATEGY"."STORAGE_OVERHEAD" IS 'Storage multiplier vs standard chunking (1.0 = no overhead)';
   COMMENT ON TABLE "AI8P"."LKP_CHUNKING_STRATEGY"  IS 'Registry of chunking strategies with metadata, best practices, and configuration';
