--------------------------------------------------------
--  DDL for Table LKP_CONTEXT_DOMAIN_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "LKP_CONTEXT_DOMAIN_CATEGORIES" 
   (	"CONTEXT_DOMAIN_CATEGORY_ID" NUMBER DEFAULT "LKP_CONTEXT_DOMAIN_CATEGORIES_SEQ"."NEXTVAL", 
	"CATEGORY_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON_CLASS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"COLOR_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
