--------------------------------------------------------
--  DDL for Table LKP_PIPELINE_STAGE
--------------------------------------------------------

  CREATE TABLE "LKP_PIPELINE_STAGE" 
   (	"STAGE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STAGE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STAGE_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER, 
	"ICON_CLASS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"COLOR_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TARGET_TABLE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON COLUMN "LKP_PIPELINE_STAGE"."STAGE_CODE" IS 'Unique stage code used in log_core.pipeline_stage';
   COMMENT ON COLUMN "LKP_PIPELINE_STAGE"."TARGET_TABLE" IS 'Specialized audit table for this stage';
   COMMENT ON TABLE "LKP_PIPELINE_STAGE"  IS 'Valid pipeline stages for audit logging';
