--------------------------------------------------------
--  DDL for Table LKP_REGISTRY_SENSITIVITY_LEVELS
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS" 
   (	"SENSITIVITY_LEVEL" NUMBER, 
	"SENSITIVITY_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"SENSITIVITY_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"UPDATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON_CSS_CLASS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"UNICODE_ICON" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON COLUMN "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS"."SENSITIVITY_LEVEL" IS 'Numeric classification level (1=Public, 2=Internal, 3=Confidential, 4=Restricted/Payroll)';
   COMMENT ON COLUMN "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS"."SENSITIVITY_CODE" IS 'Short code for classification type';
   COMMENT ON COLUMN "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS"."SENSITIVITY_NAME" IS 'Full classification name';
   COMMENT ON COLUMN "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS"."DESCRIPTION" IS 'Description of the classification level';
   COMMENT ON TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS"  IS 'Standard classification levels for RAG data sources. Used by CONTEXT_REGISTRY.SENSITIVITY_LEVEL.';
