--------------------------------------------------------
--  DDL for Table LKP_DEBUG_LEVEL
--------------------------------------------------------

  CREATE TABLE "LKP_DEBUG_LEVEL" 
   (	"DEBUG_LEVEL_ID" NUMBER, 
	"DEBUG_LEVEL" NUMBER, 
	"LEVEL_CODE" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"LEVEL_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
