--------------------------------------------------------
--  DDL for Table LKP_DOC_RELATION_TYPE
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_DOC_RELATION_TYPE" 
   (	"RELATION_TYPE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"RELATION_TYPE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"RELATION_DESC" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
