--------------------------------------------------------
--  DDL for Table LKP_DOC_STATUS
--------------------------------------------------------

  CREATE TABLE "AI8P"."LKP_DOC_STATUS" 
   (	"STATUS_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON_UNICODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON COLUMN "AI8P"."LKP_DOC_STATUS"."STATUS_CODE" IS 'Short code identifier of the status.';
   COMMENT ON COLUMN "AI8P"."LKP_DOC_STATUS"."STATUS_NAME" IS 'Human-readable name of the status.';
   COMMENT ON TABLE "AI8P"."LKP_DOC_STATUS"  IS 'Lifecycle status of documents.';
