--------------------------------------------------------
--  DDL for Table LLM_PROVIDER_MODELS
--------------------------------------------------------

  CREATE TABLE "AI8P"."LLM_PROVIDER_MODELS" 
   (	"PROVIDER_MODEL_ID" NUMBER DEFAULT "AI8P"."CFG_MODEL_ENDPOINTS_SEQ"."NEXTVAL", 
	"MODEL_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_CODE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PROVIDER_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_VERSION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"API_BASE_URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"API_ENDPOINT_PATH" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '/chat/completions', 
	"API_KEY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTH_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'BEARER_TOKEN', 
	"AUTH_HEADER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Authorization', 
	"CUSTOM_HEADERS" JSON, 
	"CONTEXT_WINDOW_TOKENS" NUMBER DEFAULT 4096, 
	"MAX_OUTPUT_TOKENS" NUMBER DEFAULT 4096, 
	"SUPPORTS_STREAMING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"SUPPORTS_FUNCTION_CALLING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"SUPPORTS_VISION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"SUPPORTS_JSON_MODE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"DEFAULT_TEMPERATURE" NUMBER(3,2) DEFAULT 0.7, 
	"DEFAULT_TOP_P" NUMBER(4,3) DEFAULT 1.0, 
	"DEFAULT_FREQUENCY_PENALTY" NUMBER(3,2) DEFAULT 0.0, 
	"DEFAULT_PRESENCE_PENALTY" NUMBER(3,2) DEFAULT 0.0, 
	"COST_PER_1K_INPUT_TOKENS" NUMBER(10,6), 
	"COST_PER_1K_OUTPUT_TOKENS" NUMBER(10,6), 
	"RATE_LIMIT_RPM" NUMBER, 
	"RATE_LIMIT_TPM" NUMBER, 
	"PROVIDER_CONFIG" JSON, 
	"EMBEDDING_DIMENSIONS" NUMBER, 
	"MODEL_FAMILY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_SIZE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PERFORMANCE_TIER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RECOMMENDED_USE_CASE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPRECATION_DATE" DATE, 
	"REPLACEMENT_MODEL_ID" NUMBER, 
	"IS_DEFAULT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"IS_EMBEDDING_MODEL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"IS_PRODUCTION_READY" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"REQUIRES_APPROVAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_DATE" DATE, 
	"LAST_TESTED_DATE" DATE, 
	"LAST_TEST_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER DEFAULT 100, 
	"DEFAULT_TOP_K" NUMBER, 
	"PRICING_JSON" JSON
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 JSON ("CUSTOM_HEADERS") STORE AS ( CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 JSON ("PROVIDER_CONFIG") STORE AS ( CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 JSON ("PRICING_JSON") STORE AS ( CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "AI8P"."LLM_PROVIDER_MODELS"."MODEL_NAME" IS 'User-friendly name shown in APEX LOV (must be unique)';
   COMMENT ON COLUMN "AI8P"."LLM_PROVIDER_MODELS"."MODEL_CODE" IS 'EXACT model identifier used in API calls (e.g., gpt-4o-mini, claude-sonnet-4-20250514)';
   COMMENT ON COLUMN "AI8P"."LLM_PROVIDER_MODELS"."PROVIDER_CODE" IS 'Provider identifier for routing: OPENAI, ANTHROPIC, GOOGLE, HUGGINGFACE, LOCAL';
   COMMENT ON COLUMN "AI8P"."LLM_PROVIDER_MODELS"."CONTEXT_WINDOW_TOKENS" IS 'Maximum total tokens including input + output for this model';
   COMMENT ON COLUMN "AI8P"."LLM_PROVIDER_MODELS"."COST_PER_1K_INPUT_TOKENS" IS 'Cost in USD per 1000 input tokens for budget tracking';
   COMMENT ON TABLE "AI8P"."LLM_PROVIDER_MODELS"  IS 'Multi-provider LLM endpoint configuration supporting OpenAI, Claude, Gemini, HuggingFace, and local models';
