--------------------------------------------------------
--  DDL for Table LOG_ARCHIVE_STORE
--------------------------------------------------------

  CREATE TABLE "AI8P"."LOG_ARCHIVE_STORE" 
   (	"ARCHIVE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"PAYLOAD" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
 LOB ("PAYLOAD") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
