--------------------------------------------------------
--  DDL for Table RAG_DOMAIN_SOURCES
--------------------------------------------------------

  CREATE TABLE "AI8P"."RAG_DOMAIN_SOURCES" 
   (	"DOMAIN_SOURCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTEXT_DOMAIN_ID" NUMBER, 
	"RAG_REGISTRY_ID" NUMBER, 
	"PRIORITY" NUMBER DEFAULT 50, 
	"IS_MANDATORY" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"WEIGHT" NUMBER(5,2) DEFAULT 1.0, 
	"MIN_RELEVANCE_SCORE" NUMBER(3,2), 
	"MAX_RESULTS" NUMBER, 
	"NOTES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
