--------------------------------------------------------
--  DDL for Table SEGMENT_USERS
--------------------------------------------------------

  CREATE TABLE "AI8P"."SEGMENT_USERS" 
   (	"SEGMENT_USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SEGMENT_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"ASSIGNED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ASSIGNED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"ASSIGNMENT_METHOD" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING;

   COMMENT ON TABLE "AI8P"."SEGMENT_USERS"  IS 'Association between user segments and individual users';
