--------------------------------------------------------
--  DDL for Table SHADOW_COMPARISON_LOG
--------------------------------------------------------

  CREATE TABLE "AI8P"."SHADOW_COMPARISON_LOG" 
   (	"COMPARISON_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHADOW_DEPLOYMENT_ID" NUMBER, 
	"PRODUCTION_DEPLOYMENT_ID" NUMBER, 
	"PRODUCTION_CALL_ID" NUMBER, 
	"SHADOW_CALL_ID" NUMBER, 
	"COMPARISON_RESULT" JSON, 
	"RESPONSE_MATCH_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SIMILARITY_SCORE" NUMBER(5,2), 
	"LATENCY_DIFFERENCE_MS" NUMBER, 
	"COST_DIFFERENCE_USD" NUMBER(10,6), 
	"COMPARED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
 JSON ("COMPARISON_RESULT") STORE AS ( CHUNK 8192 RETENTION MIN 1800) ;

   COMMENT ON TABLE "AI8P"."SHADOW_COMPARISON_LOG"  IS 'Comparison results between shadow and production deployments';
