--------------------------------------------------------
--  DDL for Table USER_SEGMENT_ASSIGNMENTS
--------------------------------------------------------

  CREATE TABLE "AI8P"."USER_SEGMENT_ASSIGNMENTS" 
   (	"ASSIGNMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"SEGMENT_ID" NUMBER, 
	"DEPLOYMENT_ID" NUMBER, 
	"EXPERIMENT_ID" NUMBER, 
	"ASSIGNMENT_METHOD" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSIGNMENT_HASH" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSIGNED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"STICKY_UNTIL" TIMESTAMP (6), 
	"ASSIGNMENT_METADATA" JSON, 
	"CREATED_BY" NUMBER, 
	"UPDATED_AT" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
 JSON ("ASSIGNMENT_METADATA") STORE AS ( CHUNK 8192 RETENTION MIN 1800) ;

   COMMENT ON COLUMN "AI8P"."USER_SEGMENT_ASSIGNMENTS"."ASSIGNMENT_HASH" IS 'Hash value used for consistent user assignment across sessions';
   COMMENT ON COLUMN "AI8P"."USER_SEGMENT_ASSIGNMENTS"."STICKY_UNTIL" IS 'User stays in segment until this timestamp (prevents mid-experiment switching)';
   COMMENT ON TABLE "AI8P"."USER_SEGMENT_ASSIGNMENTS"  IS 'User-to-segment mappings with temporal validity for experiments';
