--------------------------------------------------------
--  DDL for Table USER_SEGMENTS
--------------------------------------------------------

  CREATE TABLE "AI8P"."USER_SEGMENTS" 
   (	"SEGMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SEGMENT_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FILTER_CRITERIA" CLOB COLLATE "USING_NLS_COMP", 
	"FILTER_CRITERIA_JSON" JSON, 
	"CURRENT_USER_COUNT" NUMBER DEFAULT 0, 
	"IS_ACTIVE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"LAST_REFRESHED_AT" TIMESTAMP (6), 
	"LAST_REFRESHED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("FILTER_CRITERIA") STORE AS SECUREFILE (ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 JSON ("FILTER_CRITERIA_JSON") STORE AS ( CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "AI8P"."USER_SEGMENTS"."SEGMENT_TYPE" IS 'STATIC=Fixed list, DYNAMIC=Query-based, PERCENTAGE=Random sample, GEOGRAPHIC=Location-based, CUSTOM=Complex rules';
   COMMENT ON COLUMN "AI8P"."USER_SEGMENTS"."FILTER_CRITERIA" IS 'SQL WHERE clause for DYNAMIC segments';
   COMMENT ON COLUMN "AI8P"."USER_SEGMENTS"."FILTER_CRITERIA_JSON" IS 'JSON criteria for CUSTOM segments';
   COMMENT ON TABLE "AI8P"."USER_SEGMENTS"  IS 'User segments for targeted deployment assignments';
