--------------------------------------------------------
--  DDL for Table USER_ROLES
--------------------------------------------------------

  CREATE TABLE "USER_ROLES" 
   (	"USER_ROLE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"IS_PRIMARY" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"EFFECTIVE_FROM" DATE DEFAULT SYSDATE, 
	"EFFECTIVE_TO" DATE, 
	"ASSIGNED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSIGNMENT_REASON" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"IS_ACTIVE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
