--------------------------------------------------------
--  DDL for Table XXXCFG_PARAM_AUDIT
--------------------------------------------------------

  CREATE TABLE "XXXCFG_PARAM_AUDIT" 
   (	"AUDIT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PARAM_ID" NUMBER, 
	"TENANT_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APP_ID" NUMBER, 
	"ACTION_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"OLD_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEW_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_SECRET" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"CHANGED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	"CHANGED_ON" DATE DEFAULT SYSDATE, 
	"REMARKS" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
