--------------------------------------------------------
--  DDL for Package EMBEDDING_PROCESSOR_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "AI8P"."EMBEDDING_PROCESSOR_PKG" AS
/**
 * PROJECT:     Oracle AI ChatPot - Enterprise RAG System
 * MODULE:      EMBEDDING_PROCESSOR_PKG (Specification)
 * PURPOSE:     Orchestration of Chunk Vectorization and Syncing.
 *
 * DESCRIPTION: Coordinates the lifecycle of document embeddings. It transforms 
 * text chunks generated by the processor into vector representations 
 * using specified AI models. Supports bulk processing and 
 * maintenance-based refreshing of vectors.
 *
 * AUTHOR:      Alaa Abdelmoneim <alaa.guru@outlook.com>
 * GITHUB:      https://github.com/AlaaEldin-AbdelMonem/oracle-apex-ai-assistant
 * LINKEDIN:    https://www.linkedin.com/in/alaa-eldin/
 * LICENSE:     MIT
 * COPYRIGHT:   (c) 2026 Alaa Abdelmoneim
 *
 * VERSION:     1.0.0
 * DATABASE:    Oracle Database 23ai
 */

    -- Package Metadata
    c_version       CONSTANT VARCHAR2(10) := '1.0.0';
    c_package_name  CONSTANT VARCHAR2(30) := 'EMBEDDING_PROCESSOR_PKG'; 

    /*******************************************************************************
     * VECTORIZATION API
     *******************************************************************************/

    /**
     * Function: embed_document_chunks
     * Iterates through all chunks of a document and generates their vector embeddings.
     * * @param p_doc_id          The unique identifier of the document.
     * @param p_strategy        The chunking strategy used (for logging/metadata).
     * @param p_chunk_size      The size of chunks being processed.
     * @param p_embedding_model The vector model to utilize (Default: E5_MULTILINGUAL).
     * @return NUMBER           The total count of chunks successfully embedded.
     */
    FUNCTION embed_document_chunks(
        p_doc_id           IN NUMBER,
        p_strategy         IN VARCHAR2,
        p_chunk_size       IN NUMBER,
        p_embedding_model  IN VARCHAR2 DEFAULT 'E5_MULTILINGUAL'
    ) RETURN NUMBER;

    /*******************************************************************************
     * MAINTENANCE & SYNCHRONIZATION
     *******************************************************************************/

    /**
     * Procedure: refresh_embeddings
     * Re-calculates embeddings for documents. Useful if the embedding model 
     * changes or if vectors need to be re-synced.
     * * @param p_doc_id        If NULL, processes all documents requiring refresh.
     * @param p_force_refresh If TRUE, ignores existing vectors and re-generates all.
     */
    PROCEDURE refresh_embeddings(
        p_doc_id         IN NUMBER  DEFAULT NULL,
        p_force_refresh  IN BOOLEAN DEFAULT FALSE
    );

END embedding_processor_pkg;

/
