--------------------------------------------------------
--  DDL for Index APP_ENVIRONMENT_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "AI8P"."APP_ENVIRONMENT_UNQ" ON "AI8P"."APP_ENVIRONMENT" ("ENV_CODE", "TENANT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
