--------------------------------------------------------
--  DDL for Index IDX_CHUNK_STRAT_DEFAULT
--------------------------------------------------------

  CREATE INDEX "IDX_CHUNK_STRAT_DEFAULT" ON "LKP_CHUNKING_STRATEGY" ("IS_DEFAULT") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
