--------------------------------------------------------
--  DDL for Index IDX_ENT_AI_DOCS_CHUNK_STRAT
--------------------------------------------------------

  CREATE INDEX "AI8P"."IDX_ENT_AI_DOCS_CHUNK_STRAT" ON "AI8P"."DOCS" ("CHUNKING_STRATEGY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
