--------------------------------------------------------
--  DDL for Index IDX_CFG_AUDIT_DATE
--------------------------------------------------------

  CREATE INDEX "AI8P"."IDX_CFG_AUDIT_DATE" ON "AI8P"."XXXCFG_PARAM_AUDIT" ("CHANGED_ON") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
