--------------------------------------------------------
--  DDL for Index IDX_GOV_CATEGORY
--------------------------------------------------------

  CREATE INDEX "IDX_GOV_CATEGORY" ON "CFG_GOVERNANCE_RULES" ("RULE_CATEGORY", "IS_ACTIVE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
