--------------------------------------------------------
--  DDL for Index IDX_BEHAVIOR_ACTIVE
--------------------------------------------------------

  CREATE INDEX "IDX_BEHAVIOR_ACTIVE" ON "LKP_CONTEXT_DOMAIN_BEHAVIORS" ("IS_ACTIVE", "DISPLAY_ORDER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
