--------------------------------------------------------
--  DDL for Index IDX_MODE_SOURCES_REGISTRY
--------------------------------------------------------

  CREATE INDEX "AI8P"."IDX_MODE_SOURCES_REGISTRY" ON "AI8P"."RAG_DOMAIN_SOURCES" ("RAG_REGISTRY_ID", "IS_ACTIVE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
