--------------------------------------------------------
--  DDL for Index IDX_MODEL_COST
--------------------------------------------------------

  CREATE INDEX "IDX_MODEL_COST" ON "LLM_PROVIDER_MODELS" ("COST_PER_1K_INPUT_TOKENS", "COST_PER_1K_OUTPUT_TOKENS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
