--------------------------------------------------------
--  DDL for Index IDX_FORMAT_ACTIVE
--------------------------------------------------------

  CREATE INDEX "AI8P"."IDX_FORMAT_ACTIVE" ON "AI8P"."LKP_OUTPUT_FORMAT" ("IS_ACTIVE", "DISPLAY_ORDER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
