--------------------------------------------------------
--  DDL for Index IX_AUDIT_USER_TIME
--------------------------------------------------------

  CREATE INDEX "IX_AUDIT_USER_TIME" ON "DEBUG_AUDIT_LOG" ("USER_ID", "CREATED_AT") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
