--------------------------------------------------------
--  DDL for Index LKP_MIME_TYPES_CAT_IX
--------------------------------------------------------

  CREATE INDEX "LKP_MIME_TYPES_CAT_IX" ON "LKP_MIME_TYPES" ("MIME_CATEGORY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
