--------------------------------------------------------
--  DDL for Index PK_LKP_DEBUG_AUDIT_EVENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_LKP_DEBUG_AUDIT_EVENTS" ON "LKP_DEBUG_AUDIT_EVENTS" ("EVENT_CODE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
