--------------------------------------------------------
--  DDL for Index PK_LKP_CLEARANCE_LEVELS
--------------------------------------------------------

  CREATE UNIQUE INDEX "AI8P"."PK_LKP_CLEARANCE_LEVELS" ON "AI8P"."LKP_ROLE_CLEARANCE_LEVELS" ("CLEARANCE_LEVEL") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
