--------------------------------------------------------
--  DDL for Index UK_LKP_SENSITIVITY_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_LKP_SENSITIVITY_CODE" ON "LKP_REGISTRY_SENSITIVITY_LEVELS" ("SENSITIVITY_CODE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
