--------------------------------------------------------
--  DDL for Index UK_MODEL_API_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "AI8P"."UK_MODEL_API_ID" ON "AI8P"."LLM_PROVIDER_MODELS" ("MODEL_CODE", "PROVIDER_CODE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
