--------------------------------------------------------
--  DDL for Index UK_MODE_BEHAVIOR_FORMAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_MODE_BEHAVIOR_FORMAT" ON "CONTEXT_DOMAIN_BEHAVIORS" ("CONTEXT_DOMAIN_ID", "DOMAIN_BEHAVIOR_CODE", "FORMAT_CODE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
