--------------------------------------------------------
--  DDL for Index UK_MODE_SOURCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "AI8P"."UK_MODE_SOURCE" ON "AI8P"."RAG_DOMAIN_SOURCES" ("CONTEXT_DOMAIN_ID", "RAG_REGISTRY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
