--------------------------------------------------------
--  DDL for Index UK_USER_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_USER_ROLE" ON "USER_ROLES" ("USER_ID", "ROLE_ID", "EFFECTIVE_FROM") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
