--------------------------------------------------------
--  DDL for Index UQ_CFG_PARAM_CTX
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_CFG_PARAM_CTX" ON "CFG_PARAMETERS" ("TENANT_ID", "APP_ID", "PARAM_KEY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
