prompt --application/shared_components/user_interface/templates/report/axa
begin
--   Manifest
--     ROW TEMPLATE: AXA
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>110979332345909267
,p_default_application_id=>119
,p_default_id_offset=>0
,p_default_owner=>'AI8P'
);
wwv_flow_imp_shared.create_row_template(
 p_id=>wwv_flow_imp.id(149347685954812285)
,p_row_template_name=>'ax'
,p_internal_name=>'AXA'
,p_row_template1=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<style>',
'/* ================================',
'   SESSION HEADER COMPONENT STYLES',
'   ================================= */',
'.session-header-bar {',
'    background: #fff;',
'    border-bottom: 1px solid #d9d9d9;',
'    padding: 8px 12px;',
'    display: flex;',
'    align-items: center;',
'    width: 100%;',
'}',
'',
'.session-header-content {',
'    display: flex;',
'    justify-content: space-between;',
'    align-items: center;',
'    width: 100%;',
'}',
'',
'.session-title-container {',
'    display: flex;',
'    align-items: center;',
'    gap: 6px;',
'}',
'',
'.session-title-text {',
'    font-size: 15px;',
'    font-weight: 500;',
'}',
'',
'.session-title-edit {',
'    padding: 2px 6px;',
'    font-size: 14px !important;',
'}',
'',
'.separator {',
'    color: #777;',
'    font-weight: 600;',
'}',
'',
'.session-actions-menu {',
'    position: relative;',
'}',
'',
'.apex-menu {',
'    position: absolute;',
'    right: 0;',
'    top: 30px;',
'    background: #fff;',
'    border-radius: 4px;',
'    border: 1px solid #ccc;',
'    min-width: 200px;',
'    padding: 4px 0;',
'    box-shadow: 0 4px 8px rgba(0,0,0,0.15);',
'    z-index: 9999;',
'}',
'',
'.apex-menu-item {',
'    list-style: none;',
'}',
'',
'.apex-menu-link {',
'    display: flex;',
'    align-items: center;',
'    gap: 8px;',
'    padding: 6px 12px;',
'    color: #333;',
'    text-decoration: none;',
'}',
'',
'.apex-menu-link:hover {',
'    background: #f0f0f0;',
'}',
'',
'.apex-menu-item-danger .apex-menu-link {',
'    color: #d10000;',
'}',
'',
'.apex-menu-item-danger .apex-menu-link:hover {',
'    background: #ffe6e6;',
'}',
'',
'.apex-menu-separator {',
'    border-top: 1px solid #ddd;',
'    margin: 3px 0;',
'}',
'</style>',
'',
'<!-- ================================',
'     SESSION HEADER COMPONENT HTML',
'     ================================ -->',
'<div class="session-header-bar">',
'    <div class="session-header-content">',
'',
'        <!-- Left: Project >> Session Title -->',
'        <div class="session-title-container">',
'',
'            <span class="session-title-display"',
'                  data-session-id="#CHAT_SESSION_ID#"',
'                  data-project-id="#CHAT_PROJECT_ID#">',
'',
'                <!-- PROJECT BADGE -->',
'                <span class="project-badge t-Badge t-Badge--info"',
'                      title="Project: #CHAT_PROJECT_TITLE#">',
unistr('                    <span class="t-Badge-label">\D83D\DCC1 #CHAT_PROJECT_TITLE#</span>'),
'                </span>',
'',
unistr('                <span class="separator">\203A</span>'),
'',
'                <!-- SESSION TITLE DISPLAY -->',
'                <span id="sessionTitle_#CHAT_SESSION_ID#"',
'                      class="session-title-text">',
'                    #CHAT_SESSION_TITLE#',
'                </span>',
'',
'                <!-- HIDDEN EDIT FIELD -->',
'                <input type="text"',
'                       id="sessionTitleEdit_#CHAT_SESSION_ID#"',
'                       class="session-title-edit apex-item-text"',
'                       value="#CHAT_SESSION_TITLE#"',
'                       style="display:none;"',
'                       data-session-id="#CHAT_SESSION_ID#">',
'            </span>',
'',
'            <!-- Edit Button -->',
'            <button class="session-edit-btn t-Button t-Button--noLabel t-Button--icon t-Button--small"',
'                    type="button"',
'                    title="Edit session title"',
'                    data-session-id="#CHAT_SESSION_ID#"',
'                    onclick="toggleEditMode(''#CHAT_SESSION_ID#'')">',
'                <span class="t-Icon fa fa-pencil"></span>',
'            </button>',
'',
'            <!-- Save Button -->',
'            <button class="session-save-btn t-Button t-Button--noLabel t-Button--icon t-Button--small t-Button--success"',
'                    type="button"',
'                    title="Save"',
'                    id="saveBtn_#CHAT_SESSION_ID#"',
'                    style="display:none;"',
'                    data-session-id="#CHAT_SESSION_ID#">',
'                <span class="t-Icon fa fa-check"></span>',
'            </button>',
'',
'            <!-- Cancel Button -->',
'            <button class="session-cancel-btn t-Button t-Button--noLabel t-Button--icon t-Button--small"',
'                    type="button"',
'                    title="Cancel"',
'                    id="cancelBtn_#CHAT_SESSION_ID#"',
'                    style="display:none;"',
'                    onclick="cancelEdit(''#CHAT_SESSION_ID#'')">',
'                <span class="t-Icon fa fa-times"></span>',
'            </button>',
'        </div>',
'',
'        <!-- Right: Actions Menu -->',
'        <div class="session-actions-menu">',
'            <button class="t-Button t-Button--noLabel t-Button--icon"',
'                    type="button"',
'                    id="sessionMenu_#CHAT_SESSION_ID#"',
'                    aria-label="Session options"',
'                    onclick="toggleMenu(''#CHAT_SESSION_ID#'')">',
'                <span class="t-Icon fa fa-ellipsis-v"></span>',
'            </button>',
'',
'            <!-- Dropdown Menu -->',
'            <ul class="apex-menu" id="sessionMenuList_#CHAT_SESSION_ID#" style="display:none;">',
'                <li class="apex-menu-item">',
'                    <a href="#" class="apex-menu-link" data-action="edit-title" data-session-id="#CHAT_SESSION_ID#">',
'                        <span class="t-Icon fa fa-pencil"></span>',
'                        Edit Session Title',
'                    </a>',
'                </li>',
'',
'                <li class="apex-menu-item">',
'                    <a href="#" class="apex-menu-link" data-action="copy-title" data-session-id="#CHAT_SESSION_ID#">',
'                        <span class="t-Icon fa fa-copy"></span>',
'                        Copy Title',
'                    </a>',
'                </li>',
'',
'                <li class="apex-menu-item">',
'                    <a href="#REPORT_ISSUE_URL#" class="apex-menu-link">',
'                        <span class="t-Icon fa fa-flag"></span>',
'                        Report Session Issue',
'                    </a>',
'                </li>',
'',
'                <li class="apex-menu-item">',
'                    <a href="#" class="apex-menu-link" data-action="export-session" data-session-id="#CHAT_SESSION_ID#">',
'                        <span class="t-Icon fa fa-download"></span>',
'                        Export Conversation',
'                    </a>',
'                </li>',
'',
'                <li class="apex-menu-item">',
'                    <a href="#" class="apex-menu-link" data-action="reassign-project" data-session-id="#CHAT_SESSION_ID#">',
'                        <span class="t-Icon fa fa-folder-open"></span>',
'                        Reassign to Project',
'                    </a>',
'                </li>',
'',
'                <li class="apex-menu-separator"></li>',
'',
'                <li class="apex-menu-item apex-menu-item-danger">',
'                    <a href="#" class="apex-menu-link" data-action="clear-session" data-session-id="#CHAT_SESSION_ID#">',
'                        <span class="t-Icon fa fa-trash"></span>',
'                        Clear Session',
'                    </a>',
'                </li>',
'            </ul>',
'        </div>',
'',
'    </div>',
'</div>',
''))
,p_row_template_before_rows=>' '
,p_row_template_after_rows=>' '
,p_row_template_type=>'NAMED_COLUMNS'
,p_row_template_display_cond1=>'0'
,p_row_template_display_cond2=>'0'
,p_row_template_display_cond3=>'0'
,p_row_template_display_cond4=>'0'
,p_theme_id=>42
,p_theme_class_id=>4
,p_translate_this_template=>'N'
);
wwv_flow_imp.component_end;
end;
/
