prompt --application/shared_components/user_interface/templates/report/chat_session_header
begin
--   Manifest
--     ROW TEMPLATE: CHAT_SESSION_HEADER
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>110979332345909267
,p_default_application_id=>119
,p_default_id_offset=>0
,p_default_owner=>'AI8P'
);
wwv_flow_imp_shared.create_row_template(
 p_id=>wwv_flow_imp.id(149338202911536075)
,p_row_template_name=>'Chat SESSION Header'
,p_internal_name=>'CHAT_SESSION_HEADER'
,p_row_template1=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<style>',
'/* SESSION HEADER BAR - APEX THEME COLORS */',
'.session-header-bar {',
'    background-color: var(--ut-component-background-color, #f8f9fa);',
'    border-bottom: 1px solid var(--ut-component-border-color, #dee2e6);',
'    padding: 12px 20px;',
'    margin-bottom: 16px;',
'    border-radius: 4px;',
'}',
'',
'.session-header-content {',
'    display: flex;',
'    justify-content: space-between;',
'    align-items: center;',
'    gap: 16px;',
'}',
'',
'.session-title-container {',
'    display: flex;',
'    align-items: center;',
'    gap: 8px;',
'    flex: 1;',
'    min-width: 0;',
'}',
'',
'.session-title-display {',
'    display: flex;',
'    align-items: center;',
'    gap: 8px;',
'    flex: 1;',
'    min-width: 0;',
'}',
'',
'.project-badge {',
'    flex-shrink: 0;',
'    max-width: 200px;',
'    overflow: hidden;',
'    text-overflow: ellipsis;',
'}',
'',
'.separator {',
'    color: var(--ut-body-text-color, #6c757d);',
'    font-weight: 300;',
'    flex-shrink: 0;',
'}',
'',
'.session-title-text {',
'    font-size: 16px;',
'    font-weight: 600;',
'    color: var(--ut-body-title-text-color, #212529);',
'    flex: 1;',
'    min-width: 0;',
'    overflow: hidden;',
'    text-overflow: ellipsis;',
'    white-space: nowrap;',
'    padding: 4px 8px;',
'}',
'',
'.session-title-edit {',
'    flex: 1;',
'    min-width: 200px;',
'    font-size: 16px;',
'    font-weight: 600;',
'}',
'',
'.session-edit-btn {',
'    opacity: 0.3;',
'    transition: opacity 0.2s;',
'}',
'',
'.session-title-container:hover .session-edit-btn {',
'    opacity: 1;',
'}',
'',
'/* APEX MENU STYLING */',
'.apex-menu {',
'    position: absolute;',
'    top: calc(100% + 8px);',
'    right: 0;',
'    min-width: 220px;',
'    background: var(--ut-component-background-color, #ffffff);',
'    border: 1px solid var(--ut-component-border-color, #dee2e6);',
'    border-radius: 4px;',
'    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);',
'    z-index: 1000;',
'    list-style: none;',
'    margin: 0;',
'    padding: 8px 0;',
'}',
'',
'.apex-menu-item {',
'    margin: 0;',
'}',
'',
'.apex-menu-link {',
'    display: flex;',
'    align-items: center;',
'    gap: 12px;',
'    padding: 10px 16px;',
'    color: var(--ut-body-text-color, #212529);',
'    text-decoration: none;',
'    transition: background-color 0.15s;',
'    cursor: pointer;',
'}',
'',
'.apex-menu-link:hover {',
'    background-color: var(--ut-component-highlight-background-color, #f1f3f5);',
'    text-decoration: none;',
'}',
'',
'.apex-menu-link .t-Icon {',
'    width: 16px;',
'    text-align: center;',
'}',
'',
'.apex-menu-item-danger .apex-menu-link {',
'    color: var(--ut-palette-danger, #dc3545);',
'}',
'',
'.apex-menu-item-danger .apex-menu-link:hover {',
'    background-color: var(--ut-palette-danger-bg, #f8d7da);',
'}',
'',
'.apex-menu-separator {',
'    height: 1px;',
'    background-color: var(--ut-component-border-color, #dee2e6);',
'    margin: 8px 0;',
'}',
'',
'@media (max-width: 768px) {',
'    .session-header-content {',
'        flex-direction: column;',
'        align-items: flex-start;',
'        gap: 12px;',
'    }',
'    .project-badge {',
'        max-width: 150px;',
'    }',
'}',
'</style>',
'',
'',
'<!-- SESSION HEADER HTML -->',
'<div class="session-header-bar">',
'    <div class="session-header-content">',
'',
'        <div class="session-title-container">',
'',
'            <span class="session-title-display" ',
'                  data-session-id="#CHAT_SESSION_ID#"',
'                  data-project-id="#CHAT_PROJECT_ID#">',
'',
'                <span class="project-badge t-Badge t-Badge--info" ',
'                      title="Project: #CHAT_PROJECT_TITLE#">',
unistr('                    <span class="t-Badge-label">\D83D\DCC1 #CHAT_PROJECT_TITLE#</span>'),
'                </span>',
'',
unistr('                <span class="separator">&nbsp;\203A&nbsp;</span>'),
'',
'                <span id="sessionTitle_#CHAT_SESSION_ID#" ',
'                      class="session-title-text">',
'                    #CHAT_SESSION_TITLE#',
'                </span>',
'',
'                <input type="text" ',
'                       id="sessionTitleEdit_#CHAT_SESSION_ID#"',
'                       class="session-title-edit apex-item-text"',
'                       value="#CHAT_SESSION_TITLE#"',
'                       style="display:none;"',
'                       data-session-id="#CHAT_SESSION_ID#" />',
'            </span>',
'',
'            <button class="session-edit-btn t-Button t-Button--noLabel t-Button--icon t-Button--small"',
'                    type="button"',
'                    title="Edit session title"',
'                    onclick="chatSession.toggleEditMode(''#CHAT_SESSION_ID#'');">',
'                <span class="t-Icon fa fa-pencil"></span>',
'            </button>',
'',
'            <button class="session-save-btn t-Button t-Button--noLabel t-Button--icon t-Button--small t-Button--success"',
'                    id="saveBtn_#CHAT_SESSION_ID#"',
'                    type="button"',
'                    style="display:none;"',
'                    onclick="chatSession.saveSessionTitle(''#CHAT_SESSION_ID#'');">',
'                <span class="t-Icon fa fa-check"></span>',
'            </button>',
'',
'            <button class="session-cancel-btn t-Button t-Button--noLabel t-Button--icon t-Button--small"',
'                    id="cancelBtn_#CHAT_SESSION_ID#"',
'                    type="button"',
'                    style="display:none;"',
'                    onclick="chatSession.cancelEdit(''#CHAT_SESSION_ID#'');">',
'                <span class="t-Icon fa fa-times"></span>',
'            </button>',
'        </div>',
'',
'        <div class="session-actions-menu">',
'            <button class="t-Button t-Button--noLabel t-Button--icon session-menu-btn"',
'                    type="button"',
'                    onclick="chatSession.toggleMenu(''#CHAT_SESSION_ID#'');">',
'                <span class="t-Icon fa fa-ellipsis-v"></span>',
'            </button>',
'        </div>',
'',
'        <ul class="apex-menu"',
'            id="sessionMenuList_#CHAT_SESSION_ID#"',
'            style="display:none;">',
'',
' ',
'            <li class="apex-menu-item">',
'                <a href="#" class="apex-menu-link" data-action="copy-title">',
'                    <span class="t-Icon fa fa-copy"></span>',
'                    Copy Title',
'                </a>',
'            </li>',
'',
'            <li class="apex-menu-item">',
'                <a href="#" class="apex-menu-link" data-action="report-session-issue" data-session-id="#CHAT_SESSION_ID#">',
'                    <span class="t-Icon fa fa-flag" aria-hidden="true"></span>',
'                    Report Session Issue',
'                </a>',
'            </li>',
'',
'            <li class="apex-menu-item">',
'                <a href="#" class="apex-menu-link" data-action="export-session">',
'                    <span class="t-Icon fa fa-download"></span>',
'                    Export Conversation',
'                </a>',
'            </li>',
'',
'            <li class="apex-menu-item">',
'                <a href="#" class="apex-menu-link" data-action="reassign-project">',
'                    <span class="t-Icon fa fa-folder-open"></span>',
'                    Reassign to Project',
'                </a>',
'            </li>',
'',
'            <li class="apex-menu-separator"></li>',
'',
'            <li class="apex-menu-item apex-menu-item-danger">',
'                <a href="#" class="apex-menu-link" data-action="clear-session">',
'                    <span class="t-Icon fa fa-trash"></span>',
'                    Clear Session',
'                </a>',
'            </li>',
'',
'        </ul>',
'',
'    </div>',
'</div>',
''))
,p_row_template_before_rows=>' '
,p_row_template_after_rows=>' '
,p_row_template_type=>'NAMED_COLUMNS'
,p_row_template_display_cond1=>'0'
,p_row_template_display_cond2=>'0'
,p_row_template_display_cond3=>'0'
,p_row_template_display_cond4=>'0'
,p_theme_id=>42
,p_theme_class_id=>4
,p_translate_this_template=>'N'
);
wwv_flow_imp.component_end;
end;
/
