--------------------------------------------------------
--  Constraints for Table AI_MODEL_PRICING
--------------------------------------------------------

  ALTER TABLE "AI_MODEL_PRICING" MODIFY ("PROVIDER" NOT NULL ENABLE);
  ALTER TABLE "AI_MODEL_PRICING" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI_MODEL_PRICING" ADD CONSTRAINT "PK_MODEL_PRICING" PRIMARY KEY ("PROVIDER", "MODEL_NAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
