--------------------------------------------------------
--  Constraints for Table AI_MODEL_USAGE
--------------------------------------------------------

  ALTER TABLE "AI_MODEL_USAGE" MODIFY ("USAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI_MODEL_USAGE" ADD PRIMARY KEY ("USAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
