--------------------------------------------------------
--  Constraints for Table APP_ADMIN_USERS
--------------------------------------------------------

  ALTER TABLE "AI8P"."APP_ADMIN_USERS" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."APP_ADMIN_USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."APP_ADMIN_USERS" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."APP_ADMIN_USERS" ADD CONSTRAINT "APP_ADMIN_USERS_U1" UNIQUE ("APP_ID", "USERNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
