--------------------------------------------------------
--  Constraints for Table APP_ENVIRONMENT
--------------------------------------------------------

  ALTER TABLE "AI8P"."APP_ENVIRONMENT" MODIFY ("ENV_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."APP_ENVIRONMENT" MODIFY ("ENV_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."APP_ENVIRONMENT" MODIFY ("ENV_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."APP_ENVIRONMENT" MODIFY ("CONFIG_KEY" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."APP_ENVIRONMENT" ADD PRIMARY KEY ("ENV_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."APP_ENVIRONMENT" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."APP_ENVIRONMENT" ADD CONSTRAINT "APP_ENVIRONMENT_UNQ" UNIQUE ("ENV_CODE", "TENANT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
