--------------------------------------------------------
--  Constraints for Table CFG_PARAM_OVERRIDES
--------------------------------------------------------

  ALTER TABLE "AI8P"."CFG_PARAM_OVERRIDES" MODIFY ("OVERRIDE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CFG_PARAM_OVERRIDES" MODIFY ("PARAM_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CFG_PARAM_OVERRIDES" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."CFG_PARAM_OVERRIDES" ADD PRIMARY KEY ("OVERRIDE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
