--------------------------------------------------------
--  Constraints for Table CFG_CONTEXT_INSTRUCTIONS
--------------------------------------------------------

  ALTER TABLE "AI8P"."CFG_CONTEXT_INSTRUCTIONS" MODIFY ("GLOBAL_INSTRUCTION_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CFG_CONTEXT_INSTRUCTIONS" ADD CONSTRAINT "CFG_GLOBAL_INSTRUCTIONS_CON" PRIMARY KEY ("GLOBAL_INSTRUCTION_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."CFG_CONTEXT_INSTRUCTIONS" ADD CONSTRAINT "CFG_GLOBAL_INSTRUCTIONS_UNQ" UNIQUE ("INSTRUCTION_TYPE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
