--------------------------------------------------------
--  Constraints for Table CFG_GOVERNANCE_RULES
--------------------------------------------------------

  ALTER TABLE "CFG_GOVERNANCE_RULES" MODIFY ("RULE_ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_GOVERNANCE_RULES" MODIFY ("RULE_CODE" NOT NULL ENABLE);
  ALTER TABLE "CFG_GOVERNANCE_RULES" MODIFY ("RULE_NAME" NOT NULL ENABLE);
  ALTER TABLE "CFG_GOVERNANCE_RULES" MODIFY ("RULE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "CFG_GOVERNANCE_RULES" ADD CHECK (rule_category IN ('GOVERNANCE','SAFETY','COMPLIANCE','ETHICS')) ENABLE;
  ALTER TABLE "CFG_GOVERNANCE_RULES" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "CFG_GOVERNANCE_RULES" ADD PRIMARY KEY ("RULE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "CFG_GOVERNANCE_RULES" ADD UNIQUE ("RULE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
