--------------------------------------------------------
--  Constraints for Table CFG_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "CFG_PARAMETERS" MODIFY ("PARAM_SCOPE" NOT NULL ENABLE);
  ALTER TABLE "CFG_PARAMETERS" MODIFY ("PARAM_ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_PARAMETERS" MODIFY ("PARAM_KEY" NOT NULL ENABLE);
  ALTER TABLE "CFG_PARAMETERS" ADD CHECK (IS_SECRET IN ('Y','N')) ENABLE;
  ALTER TABLE "CFG_PARAMETERS" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "CFG_PARAMETERS" ADD PRIMARY KEY ("PARAM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "CFG_PARAMETERS" ADD CONSTRAINT "UQ_CFG_PARAM_CTX" UNIQUE ("TENANT_ID", "APP_ID", "PARAM_KEY")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "CFG_PARAMETERS" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_PARAMETERS" MODIFY ("APP_ID" NOT NULL ENABLE);
