--------------------------------------------------------
--  Constraints for Table CFG_REDACTION_RULES
--------------------------------------------------------

  ALTER TABLE "CFG_REDACTION_RULES" MODIFY ("REDACTION_RULE_ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_REDACTION_RULES" ADD PRIMARY KEY ("REDACTION_RULE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "CFG_REDACTION_RULES" MODIFY ("RULE_ORDER" NOT NULL ENABLE);
  ALTER TABLE "CFG_REDACTION_RULES" MODIFY ("REDACTION_APPLY_PHASE_ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_REDACTION_RULES" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
