--------------------------------------------------------
--  Constraints for Table CHAT_CALL_REGENERATIONS
--------------------------------------------------------

  ALTER TABLE "AI8P"."CHAT_CALL_REGENERATIONS" MODIFY ("CHAT_CALL_REGENERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CHAT_CALL_REGENERATIONS" MODIFY ("PARENT_CHAT_CALL_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CHAT_CALL_REGENERATIONS" MODIFY ("CHILD_CHAT_CALL_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CHAT_CALL_REGENERATIONS" ADD CONSTRAINT "UK_REGEN_PAIR" UNIQUE ("PARENT_CHAT_CALL_ID", "CHILD_CHAT_CALL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
