--------------------------------------------------------
--  Constraints for Table CHAT_FAVORITES
--------------------------------------------------------

  ALTER TABLE "AI8P"."CHAT_FAVORITES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CHAT_FAVORITES" MODIFY ("CHAT_SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CHAT_FAVORITES" MODIFY ("FAVORATE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CHAT_FAVORITES" ADD CONSTRAINT "CHAT_FAVORITES_PK" PRIMARY KEY ("FAVORITE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
