--------------------------------------------------------
--  Constraints for Table CONTEXT_DOMAIN_REGISTRY
--------------------------------------------------------

  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_REGISTRY" MODIFY ("CONTEXT_DOMAIN_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_REGISTRY" MODIFY ("CONTEXT_REGISTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_REGISTRY" ADD PRIMARY KEY ("CONTEXT_DOMAIN_REGISTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
