--------------------------------------------------------
--  Constraints for Table CONTEXT_DOMAIN_BEHAVIORS
--------------------------------------------------------

  ALTER TABLE "CONTEXT_DOMAIN_BEHAVIORS" MODIFY ("CONTEXT_DOMAIN_BEHAVIOR_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAIN_BEHAVIORS" MODIFY ("CONTEXT_DOMAIN_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAIN_BEHAVIORS" MODIFY ("DOMAIN_BEHAVIOR_CODE" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAIN_BEHAVIORS" MODIFY ("FORMAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAIN_BEHAVIORS" ADD CHECK (is_default IN ('Y','N')) ENABLE;
  ALTER TABLE "CONTEXT_DOMAIN_BEHAVIORS" ADD PRIMARY KEY ("CONTEXT_DOMAIN_BEHAVIOR_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "CONTEXT_DOMAIN_BEHAVIORS" ADD CONSTRAINT "UK_MODE_BEHAVIOR_FORMAT" UNIQUE ("CONTEXT_DOMAIN_ID", "DOMAIN_BEHAVIOR_CODE", "FORMAT_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
