--------------------------------------------------------
--  Constraints for Table CONTEXT_REGISTRY
--------------------------------------------------------

  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" MODIFY ("SENSITIVITY_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" MODIFY ("CONTEXT_REGISTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" MODIFY ("SOURCE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" MODIFY ("REGISTRY_SOURCE_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" ADD CONSTRAINT "CK_RAG_SRC_TYPE" CHECK ("REGISTRY_SOURCE_TYPE_CODE"='VIEW' OR "REGISTRY_SOURCE_TYPE_CODE"='TABLE' OR "REGISTRY_SOURCE_TYPE_CODE"='PLSQL' OR "REGISTRY_SOURCE_TYPE_CODE"='API' OR "REGISTRY_SOURCE_TYPE_CODE"='CURSOR' OR "REGISTRY_SOURCE_TYPE_CODE"='DOCUMENT') ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" ADD CONSTRAINT "CK_RAG_ENABLED" CHECK ("IS_ACTIVE"='Y' OR "IS_ACTIVE"='N') ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" ADD CONSTRAINT "CK_RAG_SRC_OBJ_NAME" CHECK ("REGISTRY_SOURCE_TYPE_CODE"='DOCUMENT' OR "REGISTRY_SOURCE_TYPE_CODE"='API' OR "SOURCE_NAME" IS NOT NULL) ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" ADD CONSTRAINT "PK_RAG_SOURCE_REGISTRY" PRIMARY KEY ("CONTEXT_REGISTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY" ADD CONSTRAINT "UK_RAG_SRC_NAME" UNIQUE ("SOURCE_TITLE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
