--------------------------------------------------------
--  Constraints for Table CONTEXT_DOMAINS
--------------------------------------------------------

  ALTER TABLE "CONTEXT_DOMAINS" MODIFY ("IS_CONTEXT_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAINS" MODIFY ("CONTEXT_DOMAIN_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAINS" MODIFY ("CONTEXT_DOMAIN_CODE" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAINS" MODIFY ("DOMAIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAINS" MODIFY ("CONTEXT_DOMAIN_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_DOMAINS" ADD CHECK ("IS_DEFAULT"='Y' OR "IS_DEFAULT"='N') ENABLE;
  ALTER TABLE "CONTEXT_DOMAINS" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "CONTEXT_DOMAINS" ADD PRIMARY KEY ("CONTEXT_DOMAIN_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "CONTEXT_DOMAINS" ADD UNIQUE ("CONTEXT_DOMAIN_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
