--------------------------------------------------------
--  Constraints for Table CONTEXT_REGISTRY_ROLES
--------------------------------------------------------

  ALTER TABLE "CONTEXT_REGISTRY_ROLES" MODIFY ("CONTEXT_REGISTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_REGISTRY_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_REGISTRY_ROLES" MODIFY ("FILTER_TEMPLATE" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_REGISTRY_ROLES" ADD CONSTRAINT "CK_CONTEXT_REGISTRY_ROLES_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "CONTEXT_REGISTRY_ROLES" MODIFY ("CONTEXT_REGISTRY_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTEXT_REGISTRY_ROLES" ADD CONSTRAINT "CONTEXT_REGISTRY_ROLE_PK" PRIMARY KEY ("CONTEXT_REGISTRY_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
