--------------------------------------------------------
--  Constraints for Table DEBUG_AUDIT_LOG
--------------------------------------------------------

  ALTER TABLE "AI8P"."DEBUG_AUDIT_LOG" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."DEBUG_AUDIT_LOG" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."DEBUG_AUDIT_LOG" ADD PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
