--------------------------------------------------------
--  Constraints for Table DEPLOYMENT_AUDIT_LOG
--------------------------------------------------------

  ALTER TABLE "DEPLOYMENT_AUDIT_LOG" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_AUDIT_LOG" MODIFY ("DEPLOYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_AUDIT_LOG" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_AUDIT_LOG" ADD CONSTRAINT "CHK_DEPLOY_AUDIT_EVENT_TYPE" CHECK (event_type IN (
        'CREATED', 'ACTIVATED', 'PAUSED', 'RESUMED', 'DEACTIVATED', 'PROMOTED',
        'ROLLOUT_INCREASED', 'ROLLOUT_DECREASED', 'CONFIG_CHANGED', 
        'SEGMENT_ASSIGNED', 'SEGMENT_REMOVED', 'METRICS_THRESHOLD_BREACH',
        'SHADOW_STARTED', 'SHADOW_STOPPED', 'EXPERIMENT_COMPLETED'
    )) ENABLE;
  ALTER TABLE "DEPLOYMENT_AUDIT_LOG" ADD PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
