--------------------------------------------------------
--  Constraints for Table DEPLOYMENT_METRICS
--------------------------------------------------------

  ALTER TABLE "AI8P"."DEPLOYMENT_METRICS" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."DEPLOYMENT_METRICS" MODIFY ("DEPLOYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."DEPLOYMENT_METRICS" ADD PRIMARY KEY ("METRIC_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
  ALTER TABLE "AI8P"."DEPLOYMENT_METRICS" ADD CONSTRAINT "UK_DEPLOY_METRICS" UNIQUE ("DEPLOYMENT_ID", "SEGMENT_ID", "METRIC_DATE", "METRIC_HOUR")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
