--------------------------------------------------------
--  Constraints for Table DEPLOYMENT_VERSIONS
--------------------------------------------------------

  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD CONSTRAINT "CHK_DEPLOY_VER_TYPE" CHECK (deployment_type IN ('PRODUCTION', 'SHADOW', 'CANARY', 'AB_TEST', 'DRAFT')) ENABLE;
  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD CONSTRAINT "CHK_DEPLOY_VER_STATUS" CHECK (deployment_status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED')) ENABLE;
  ALTER TABLE "DEPLOYMENT_VERSIONS" MODIFY ("DEPLOYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_VERSIONS" MODIFY ("DEPLOYMENT_UUID" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_VERSIONS" MODIFY ("DEPLOYMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_VERSIONS" MODIFY ("DEPLOYMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_VERSIONS" MODIFY ("PROVIDER" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_VERSIONS" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_VERSIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD CONSTRAINT "CHK_DEPLOY_VER_ACTIVE" CHECK (is_active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD CONSTRAINT "CHK_DEPLOY_VER_ROLLOUT" CHECK (rollout_percentage BETWEEN 0 AND 100) ENABLE;
  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD CONSTRAINT "CHK_DEPLOY_VER_SHADOW_MODE" CHECK (shadow_execution_mode IN ('SYNC', 'ASYNC', 'SCHEDULED')) ENABLE;
  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD PRIMARY KEY ("DEPLOYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD CONSTRAINT "UK_DEPLOYMENT_VER_UUID" UNIQUE ("DEPLOYMENT_UUID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
  ALTER TABLE "DEPLOYMENT_VERSIONS" ADD CONSTRAINT "UK_DEPLOYMENT_VER_NAME" UNIQUE ("DEPLOYMENT_NAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
