--------------------------------------------------------
--  Constraints for Table DOC_RELATIONS
--------------------------------------------------------

  ALTER TABLE "DOC_RELATIONS" MODIFY ("RELATION_ID" NOT NULL ENABLE);
  ALTER TABLE "DOC_RELATIONS" MODIFY ("PARENT_DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "DOC_RELATIONS" MODIFY ("CHILD_DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "DOC_RELATIONS" ADD PRIMARY KEY ("RELATION_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
