--------------------------------------------------------
--  Constraints for Table DOC_CHUNKS
--------------------------------------------------------

  ALTER TABLE "DOC_CHUNKS" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "DOC_CHUNKS" MODIFY ("CHUNK_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "DOC_CHUNKS" MODIFY ("CHUNK_TEXT" NOT NULL ENABLE);
  ALTER TABLE "DOC_CHUNKS" ADD CONSTRAINT "CHK_RAG_CHUNKS_ACTIVE" CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "DOC_CHUNKS" ADD PRIMARY KEY ("DOC_CHUNK_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
