--------------------------------------------------------
--  Constraints for Table DOCS_STAGING
--------------------------------------------------------

  ALTER TABLE "AI8P"."DOCS_STAGING" MODIFY ("STAGING_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."DOCS_STAGING" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."DOCS_STAGING" MODIFY ("STAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."DOCS_STAGING" ADD PRIMARY KEY ("STAGING_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
