--------------------------------------------------------
--  Constraints for Table DOCS
--------------------------------------------------------

  ALTER TABLE "DOCS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "DOCS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "DOCS" MODIFY ("LAST_UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "DOCS" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DOCS" MODIFY ("DOC_ID" NOT NULL ENABLE);
  ALTER TABLE "DOCS" ADD CHECK (rag_ready_flag IN ('Y','N')) ENABLE;
  ALTER TABLE "DOCS" ADD CHECK (vector_indexed_flag IN ('Y','N')) ENABLE;
  ALTER TABLE "DOCS" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "DOCS" ADD PRIMARY KEY ("DOC_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
