--------------------------------------------------------
--  Constraints for Table HCM_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HCM_EMPLOYEE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HCM_EMPLOYEE" ADD CHECK (is_active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "HCM_EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_EMPLOYEE" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
