--------------------------------------------------------
--  Constraints for Table HCM_LEAVE_BALANCE
--------------------------------------------------------

  ALTER TABLE "AI8P"."HCM_LEAVE_BALANCE" MODIFY ("BALANCE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."HCM_LEAVE_BALANCE" ADD PRIMARY KEY ("BALANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
