--------------------------------------------------------
--  Constraints for Table LKP_DEBUG_AUDIT_EVENTS
--------------------------------------------------------

  ALTER TABLE "LKP_DEBUG_AUDIT_EVENTS" MODIFY ("DISPLAY_NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_DEBUG_AUDIT_EVENTS" ADD CONSTRAINT "PK_LKP_DEBUG_AUDIT_EVENTS" PRIMARY KEY ("EVENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
