--------------------------------------------------------
--  Constraints for Table LKP_DOC_STATUS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_DOC_STATUS" ADD PRIMARY KEY ("STATUS_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
