--------------------------------------------------------
--  Constraints for Table LKP_LANGUAGE_CODE
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_LANGUAGE_CODE" MODIFY ("LANGUAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_LANGUAGE_CODE" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_LANGUAGE_CODE" ADD PRIMARY KEY ("LANGUAGE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
