--------------------------------------------------------
--  Constraints for Table LKP_MIME_TYPES
--------------------------------------------------------

  ALTER TABLE "LKP_MIME_TYPES" MODIFY ("MIME_ID" NOT NULL ENABLE);
  ALTER TABLE "LKP_MIME_TYPES" MODIFY ("MIME_TYPE" NOT NULL ENABLE);
  ALTER TABLE "LKP_MIME_TYPES" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "LKP_MIME_TYPES" ADD PRIMARY KEY ("MIME_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "LKP_MIME_TYPES" ADD UNIQUE ("MIME_TYPE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
