--------------------------------------------------------
--  Constraints for Table LKP_CHAT_ISSUE_PRIORITY
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_CHAT_ISSUE_PRIORITY" MODIFY ("CHAT_ISSUE_PRIORITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CHAT_ISSUE_PRIORITY" MODIFY ("PRIORITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CHAT_ISSUE_PRIORITY" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CHAT_ISSUE_PRIORITY" ADD CONSTRAINT "LKP_CHAT_ISSUE_PRIORITY_PK" PRIMARY KEY ("CHAT_ISSUE_PRIORITY_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
