--------------------------------------------------------
--  Constraints for Table LKP_ROLE_CLEARANCE_LEVELS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_ROLE_CLEARANCE_LEVELS" MODIFY ("CLEARANCE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_ROLE_CLEARANCE_LEVELS" MODIFY ("CLEARANCE_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_ROLE_CLEARANCE_LEVELS" MODIFY ("CLEARANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_ROLE_CLEARANCE_LEVELS" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_ROLE_CLEARANCE_LEVELS" ADD CONSTRAINT "PK_LKP_CLEARANCE_LEVELS" PRIMARY KEY ("CLEARANCE_LEVEL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LKP_ROLE_CLEARANCE_LEVELS" ADD CONSTRAINT "UK_LKP_CLEARANCE_CODE" UNIQUE ("CLEARANCE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
