--------------------------------------------------------
--  Constraints for Table LKP_CHAT_ISSUE_LEVEL
--------------------------------------------------------

  ALTER TABLE "LKP_CHAT_ISSUE_LEVEL" MODIFY ("ISSUE_LEVEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "LKP_CHAT_ISSUE_LEVEL" MODIFY ("LEVEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_CHAT_ISSUE_LEVEL" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "LKP_CHAT_ISSUE_LEVEL" ADD CONSTRAINT "LKP_CHAT_ISSUE_LEVEL_PK" PRIMARY KEY ("ISSUE_LEVEL_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
