--------------------------------------------------------
--  Constraints for Table LKP_PIPELINE_STAGE
--------------------------------------------------------

  ALTER TABLE "LKP_PIPELINE_STAGE" MODIFY ("STAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_PIPELINE_STAGE" ADD PRIMARY KEY ("STAGE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
