--------------------------------------------------------
--  Constraints for Table LKP_DOC_CATEGORY
--------------------------------------------------------

  ALTER TABLE "LKP_DOC_CATEGORY" MODIFY ("DOC_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "LKP_DOC_CATEGORY" ADD CONSTRAINT "LKP_DOC_CATEGORY_CON" UNIQUE ("DOC_CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "LKP_DOC_CATEGORY" ADD PRIMARY KEY ("CATEGORY_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
