--------------------------------------------------------
--  Constraints for Table LKP_TEXT_CHANGE_TYPE
--------------------------------------------------------

  ALTER TABLE "LKP_TEXT_CHANGE_TYPE" MODIFY ("CHANGE_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_TEXT_CHANGE_TYPE" MODIFY ("CHANGE_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "LKP_TEXT_CHANGE_TYPE" ADD PRIMARY KEY ("CHANGE_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
