--------------------------------------------------------
--  Constraints for Table LKP_OUTPUT_FORMAT
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_OUTPUT_FORMAT" MODIFY ("FORMAT_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_OUTPUT_FORMAT" MODIFY ("INSTRUCTION_TEXT" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_OUTPUT_FORMAT" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_OUTPUT_FORMAT" ADD PRIMARY KEY ("FORMAT_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LKP_OUTPUT_FORMAT" ADD CONSTRAINT "UK_FORMAT_NAME" UNIQUE ("FORMAT_NAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
