--------------------------------------------------------
--  Constraints for Table LKP_CXD_FAILURE_ACTION_OPTIONS
--------------------------------------------------------

  ALTER TABLE "LKP_CXD_FAILURE_ACTION_OPTIONS" MODIFY ("FAILURE_ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "LKP_CXD_FAILURE_ACTION_OPTIONS" MODIFY ("FAILURE_ACTION" NOT NULL ENABLE);
  ALTER TABLE "LKP_CXD_FAILURE_ACTION_OPTIONS" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "LKP_CXD_FAILURE_ACTION_OPTIONS" ADD CHECK (is_default IN ('Y','N')) ENABLE;
  ALTER TABLE "LKP_CXD_FAILURE_ACTION_OPTIONS" ADD CONSTRAINT "LKP_CXD_FAILURE_ACTION_PK" PRIMARY KEY ("FAILURE_ACTION_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
