--------------------------------------------------------
--  Constraints for Table LKP_REDACTION_APPLY_PHASE
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_REDACTION_APPLY_PHASE" MODIFY ("APPLY_PHASE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_REDACTION_APPLY_PHASE" MODIFY ("REDACTION_APPLY_PHASE_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_REDACTION_APPLY_PHASE" ADD CONSTRAINT "LKP_REDACTION_APPLY_PAHSE_PK" PRIMARY KEY ("APPLY_PHASE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
