--------------------------------------------------------
--  Constraints for Table LKP_SEARCH_TYPE
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_SEARCH_TYPE" MODIFY ("SEARCH_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_SEARCH_TYPE" ADD CHECK (uses_embeddings IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_SEARCH_TYPE" ADD CHECK (uses_keywords IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_SEARCH_TYPE" ADD CHECK (quality_score BETWEEN 1 AND 10) ENABLE;
  ALTER TABLE "AI8P"."LKP_SEARCH_TYPE" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_SEARCH_TYPE" ADD PRIMARY KEY ("SEARCH_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
