--------------------------------------------------------
--  Constraints for Table LKP_DOMAIN_DETECTION_METHODS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_DOMAIN_DETECTION_METHODS" MODIFY ("DOMAIN_DETECTION_METHOD_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_DOMAIN_DETECTION_METHODS" MODIFY ("DETECTION_METHOD_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_DOMAIN_DETECTION_METHODS" MODIFY ("DETECTION_METHOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_DOMAIN_DETECTION_METHODS" ADD CONSTRAINT "LKP_DOMAIN_ACTIVATION_TYPE_UNQ" UNIQUE ("DOMAIN_DETECTION_METHOD_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LKP_DOMAIN_DETECTION_METHODS" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_DOMAIN_DETECTION_METHODS" ADD CONSTRAINT "LKP_DOMAIN_ACTIVATION_TYPE_PK" PRIMARY KEY ("DETECTION_METHOD_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
