--------------------------------------------------------
--  Constraints for Table LKP_CHUNKING_STRATEGY
--------------------------------------------------------

  ALTER TABLE "LKP_CHUNKING_STRATEGY" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CHECK (processing_complexity IN ('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH')) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CHECK (semantic_preservation IN ('LOW', 'MEDIUM', 'HIGH', 'EXCELLENT')) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CHECK (boundary_accuracy IN ('LOW', 'MEDIUM', 'HIGH', 'EXCELLENT')) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CHECK (is_default IN ('Y','N')) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CHECK (supports_multilingual IN ('Y','N')) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CONSTRAINT "CHK_SPEED_RANGE" CHECK (relative_speed BETWEEN 0.1 AND 10.0) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD CONSTRAINT "CHK_OVERHEAD_RANGE" CHECK (storage_overhead BETWEEN 0.5 AND 5.0) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" ADD PRIMARY KEY ("STRATEGY_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "LKP_CHUNKING_STRATEGY" MODIFY ("STRATEGY_NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_CHUNKING_STRATEGY" MODIFY ("PACKAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_CHUNKING_STRATEGY" MODIFY ("FUNCTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_CHUNKING_STRATEGY" MODIFY ("CREATED_BY" NOT NULL ENABLE);
