--------------------------------------------------------
--  Constraints for Table LKP_ERROR_SEVERITY
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_ERROR_SEVERITY" MODIFY ("SEVERITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_ERROR_SEVERITY" MODIFY ("SEVERITY_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_ERROR_SEVERITY" ADD CHECK (requires_alert IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_ERROR_SEVERITY" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_ERROR_SEVERITY" ADD PRIMARY KEY ("SEVERITY_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
