--------------------------------------------------------
--  Constraints for Table LKP_DOC_RELATION_TYPE
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_DOC_RELATION_TYPE" MODIFY ("RELATION_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_DOC_RELATION_TYPE" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_DOC_RELATION_TYPE" ADD PRIMARY KEY ("RELATION_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
