--------------------------------------------------------
--  Constraints for Table LKP_REGISTERED_HANDLERS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_REGISTERED_HANDLERS" ADD CONSTRAINT "CHK_HANDLER_UC" CHECK (HANDLER_PACKAGE = UPPER(HANDLER_PACKAGE)) ENABLE;
  ALTER TABLE "AI8P"."LKP_REGISTERED_HANDLERS" ADD CONSTRAINT "PK_LKP_REG_HANDLERS" PRIMARY KEY ("HANDLER_PACKAGE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
