--------------------------------------------------------
--  Constraints for Table LKP_REGISTRY_SENSITIVITY_LEVELS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS" MODIFY ("SENSITIVITY_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS" MODIFY ("SENSITIVITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS" MODIFY ("SENSITIVITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS" ADD CONSTRAINT "PK_LKP_SENSITIVITY_LEVEL" PRIMARY KEY ("SENSITIVITY_LEVEL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LKP_REGISTRY_SENSITIVITY_LEVELS" ADD CONSTRAINT "UK_LKP_SENSITIVITY_CODE" UNIQUE ("SENSITIVITY_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
