--------------------------------------------------------
--  Constraints for Table LKP_DEBUG_LEVEL
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_DEBUG_LEVEL" MODIFY ("DEBUG_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_DEBUG_LEVEL" MODIFY ("LEVEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_DEBUG_LEVEL" ADD CONSTRAINT "LKP_DEBUG_LEVEL_PK" PRIMARY KEY ("DEBUG_LEVEL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
