--------------------------------------------------------
--  Constraints for Table LKP_CONTEXT_DOMAIN_SCOPE_TYPE
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_SCOPE_TYPE" MODIFY ("DOMAIN_SCOPE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_SCOPE_TYPE" MODIFY ("SCOPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_SCOPE_TYPE" MODIFY ("SCOPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_SCOPE_TYPE" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_SCOPE_TYPE" ADD PRIMARY KEY ("DOMAIN_SCOPE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_SCOPE_TYPE" ADD UNIQUE ("SCOPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
