--------------------------------------------------------
--  Constraints for Table LKP_CONTEXT_DOMAIN_BEHAVIORS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_BEHAVIORS" MODIFY ("BEHAVIOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_BEHAVIORS" MODIFY ("INSTRUCTION_TEXT" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_BEHAVIORS" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_BEHAVIORS" ADD PRIMARY KEY ("DOMAIN_BEHAVIOR_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LKP_CONTEXT_DOMAIN_BEHAVIORS" ADD CONSTRAINT "UK_BEHAVIOR_NAME" UNIQUE ("BEHAVIOR_NAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
