--------------------------------------------------------
--  Constraints for Table LKP_CONTEXT_REGISTRY_SOURCE_TYPES
--------------------------------------------------------

  ALTER TABLE "LKP_CONTEXT_REGISTRY_SOURCE_TYPES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "LKP_CONTEXT_REGISTRY_SOURCE_TYPES" ADD PRIMARY KEY ("CONTEXT_REGISTRY_SOURCE_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
