--------------------------------------------------------
--  Constraints for Table LLM_PROVIDER_MODELS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" MODIFY ("MODEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" MODIFY ("PROVIDER_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" MODIFY ("API_BASE_URL" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CHECK (is_default IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CHECK (is_embedding_model IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CHECK (is_production_ready IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CHECK (requires_approval IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CONSTRAINT "CHK_TEMPERATURE_RANGE" CHECK (default_temperature BETWEEN 0 AND 2) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CONSTRAINT "CHK_COST_POSITIVE" CHECK (cost_per_1k_input_tokens >= 0 AND cost_per_1k_output_tokens >= 0) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD PRIMARY KEY ("PROVIDER_MODEL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CONSTRAINT "UK_MODEL_API_ID" UNIQUE ("MODEL_CODE", "PROVIDER_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" ADD CONSTRAINT "UK_MODEL_DISPLAY_NAME" UNIQUE ("MODEL_NAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."LLM_PROVIDER_MODELS" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE);
