--------------------------------------------------------
--  Constraints for Table LLM_PROVIDERS
--------------------------------------------------------

  ALTER TABLE "AI8P"."LLM_PROVIDERS" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDERS" MODIFY ("PROVIDER_CODE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDERS" MODIFY ("IS_DEFAULT" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDERS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."LLM_PROVIDERS" ADD CONSTRAINT "LKP_LLM_PROVIDER_PK" PRIMARY KEY ("PROVIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
