--------------------------------------------------------
--  Constraints for Table RAG_DOMAIN_SOURCES
--------------------------------------------------------

  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" MODIFY ("DOMAIN_SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" MODIFY ("CONTEXT_DOMAIN_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" MODIFY ("RAG_REGISTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" ADD CHECK (is_mandatory IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" ADD CHECK (is_active IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" ADD PRIMARY KEY ("DOMAIN_SOURCE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" ADD CONSTRAINT "UK_MODE_SOURCE" UNIQUE ("CONTEXT_DOMAIN_ID", "RAG_REGISTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
