--------------------------------------------------------
--  Constraints for Table SEGMENT_USERS
--------------------------------------------------------

  ALTER TABLE "SEGMENT_USERS" MODIFY ("SEGMENT_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SEGMENT_USERS" MODIFY ("SEGMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SEGMENT_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SEGMENT_USERS" ADD PRIMARY KEY ("SEGMENT_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
