--------------------------------------------------------
--  Constraints for Table SHADOW_COMPARISON_LOG
--------------------------------------------------------

  ALTER TABLE "AI8P"."SHADOW_COMPARISON_LOG" MODIFY ("COMPARISON_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."SHADOW_COMPARISON_LOG" MODIFY ("SHADOW_DEPLOYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."SHADOW_COMPARISON_LOG" ADD PRIMARY KEY ("COMPARISON_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
