--------------------------------------------------------
--  Constraints for Table TENANTS
--------------------------------------------------------

  ALTER TABLE "TENANTS" MODIFY ("TENANT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TENANTS" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "TENANTS" MODIFY ("TENANT_CODE" NOT NULL ENABLE);
  ALTER TABLE "TENANTS" MODIFY ("TENANT_ID" NOT NULL ENABLE);
  ALTER TABLE "TENANTS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "TENANTS" ADD CONSTRAINT "TENANTS_PK" PRIMARY KEY ("TENANT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
