--------------------------------------------------------
--  Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "AI8P"."USER_ROLES" MODIFY ("USER_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."USER_ROLES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."USER_ROLES" ADD CHECK (is_primary IN ('Y', 'N')) ENABLE;
  ALTER TABLE "AI8P"."USER_ROLES" ADD PRIMARY KEY ("USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "AI8P"."USER_ROLES" ADD CONSTRAINT "UK_USER_ROLE" UNIQUE ("USER_ID", "ROLE_ID", "EFFECTIVE_FROM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
