--------------------------------------------------------
--  Constraints for Table USER_SEGMENTS
--------------------------------------------------------

  ALTER TABLE "USER_SEGMENTS" MODIFY ("SEGMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_SEGMENTS" MODIFY ("SEGMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "USER_SEGMENTS" MODIFY ("SEGMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "USER_SEGMENTS" ADD CHECK (is_active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "USER_SEGMENTS" ADD CONSTRAINT "USER_SEGMENTS_TYPE_CK" CHECK (segment_type IN ('STATIC', 'DYNAMIC', 'PERCENTAGE', 'GEOGRAPHIC', 'CUSTOM')) ENABLE;
  ALTER TABLE "USER_SEGMENTS" ADD PRIMARY KEY ("SEGMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "USER_SEGMENTS" ADD CONSTRAINT "USER_SEGMENTS_UK" UNIQUE ("SEGMENT_NAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
