--------------------------------------------------------
--  Constraints for Table USER_SEGMENT_ASSIGNMENTS
--------------------------------------------------------

  ALTER TABLE "USER_SEGMENT_ASSIGNMENTS" MODIFY ("ASSIGNMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_SEGMENT_ASSIGNMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_SEGMENT_ASSIGNMENTS" MODIFY ("SEGMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_SEGMENT_ASSIGNMENTS" ADD CONSTRAINT "CHK_SEGMENT_ASSIGN_ACTIVE" CHECK (is_active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "USER_SEGMENT_ASSIGNMENTS" ADD PRIMARY KEY ("ASSIGNMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
  ALTER TABLE "USER_SEGMENT_ASSIGNMENTS" ADD CONSTRAINT "UK_USER_SEGMENT_DEPLOY" UNIQUE ("USER_ID", "SEGMENT_ID", "DEPLOYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255  ENABLE;
