--------------------------------------------------------
--  Constraints for Table XXXCFG_PARAM_AUDIT
--------------------------------------------------------

  ALTER TABLE "AI8P"."XXXCFG_PARAM_AUDIT" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."XXXCFG_PARAM_AUDIT" MODIFY ("PARAM_ID" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."XXXCFG_PARAM_AUDIT" MODIFY ("ACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AI8P"."XXXCFG_PARAM_AUDIT" ADD CHECK (is_secret IN ('Y','N')) ENABLE;
  ALTER TABLE "AI8P"."XXXCFG_PARAM_AUDIT" ADD PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
