prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/openai_credentials.sql
@@workspace/remote_servers/openai_genai_service.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/navbar_navbarcenterselectlist_css.sql
@@application/shared_components/files/rangeslider_plugin_range_slider_js.sql
@@application/shared_components/files/rangeslider_plugin_range_slider_min_js.sql
@@application/shared_components/files/rangeslider_plugin_range_slider_css.sql
@@application/shared_components/files/rangeslider_plugin_range_slider_min_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/chat_history_access.sql
@@application/shared_components/security/authorizations/audit_page_access.sql
@@application/shared_components/security/authorizations/admin_only_policy_manager.sql
@@application/shared_components/security/authorizations/governance_dashboard_access.sql
@@application/shared_components/security/authorizations/is_admin.sql
@@application/shared_components/security/app_access_control/ai_user.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/g_app_env.sql
@@application/shared_components/logic/application_items/g_chat_project_id.sql
@@application/shared_components/logic/application_items/g_session_start.sql
@@application/shared_components/logic/application_items/g_tenant_code.sql
@@application/shared_components/logic/application_items/g_tenant_id.sql
@@application/shared_components/logic/application_items/g_tenant_name.sql
@@application/shared_components/logic/application_items/g_user_id.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/allowed_actions_list.sql
@@application/shared_components/user_interface/lovs/app_list.sql
@@application/shared_components/user_interface/lovs/app_pages_all.sql
@@application/shared_components/user_interface/lovs/app_pages_current_session.sql
@@application/shared_components/user_interface/lovs/audit_event_types.sql
@@application/shared_components/user_interface/lovs/chat_project_session_by_userid.sql
@@application/shared_components/user_interface/lovs/chat_calls_provider.sql
@@application/shared_components/user_interface/lovs/chat_issue_level.sql
@@application/shared_components/user_interface/lovs/chat_issue_priority.sql
@@application/shared_components/user_interface/lovs/chat_issue_status.sql
@@application/shared_components/user_interface/lovs/chat_messages_message_role.sql
@@application/shared_components/user_interface/lovs/chat_sessions.sql
@@application/shared_components/user_interface/lovs/chat_sessions_session_uuid.sql
@@application/shared_components/user_interface/lovs/classification_level_list.sql
@@application/shared_components/user_interface/lovs/clearance_role_levels_list.sql
@@application/shared_components/user_interface/lovs/context_domains_code.sql
@@application/shared_components/user_interface/lovs/context_domains_id.sql
@@application/shared_components/user_interface/lovs/context_registry_source_title.sql
@@application/shared_components/user_interface/lovs/data_classification_list.sql
@@application/shared_components/user_interface/lovs/data_classification_code_list.sql
@@application/shared_components/user_interface/lovs/debug_level_debug_level.sql
@@application/shared_components/user_interface/lovs/debug_level_level_codel.sql
@@application/shared_components/user_interface/lovs/debug_scope_code.sql
@@application/shared_components/user_interface/lovs/debug_scope_id.sql
@@application/shared_components/user_interface/lovs/deployment_experiments_experiment_name.sql
@@application/shared_components/user_interface/lovs/deployment_versions_deployment_uuid.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/docs_title.sql
@@application/shared_components/user_interface/lovs/doc_status_list.sql
@@application/shared_components/user_interface/lovs/domain_activation_options_code.sql
@@application/shared_components/user_interface/lovs/domain_scope_types_list_code.sql
@@application/shared_components/user_interface/lovs/error_severity_type_list.sql
@@application/shared_components/user_interface/lovs/hcm_employee_full_name.sql
@@application/shared_components/user_interface/lovs/is_active_3.sql
@@application/shared_components/user_interface/lovs/lkp_chunking_strategy_strategy_name.sql
@@application/shared_components/user_interface/lovs/lkp_context_domain_categories_category_code.sql
@@application/shared_components/user_interface/lovs/lkp_context_domain_scope_type_scope_code.sql
@@application/shared_components/user_interface/lovs/lkp_doc_category_category_name.sql
@@application/shared_components/user_interface/lovs/lkp_domain_detection_methods_detection_method_name.sql
@@application/shared_components/user_interface/lovs/llm_models_code.sql
@@application/shared_components/user_interface/lovs/llm_models_id.sql
@@application/shared_components/user_interface/lovs/llm_providers_code_active.sql
@@application/shared_components/user_interface/lovs/lov_llm_models.sql
@@application/shared_components/user_interface/lovs/lov_llm_providers.sql
@@application/shared_components/user_interface/lovs/redaction_apply_phase_lkp.sql
@@application/shared_components/user_interface/lovs/registry_source_types_list.sql
@@application/shared_components/user_interface/lovs/roles_role_code.sql
@@application/shared_components/user_interface/lovs/sensitivity_levels_list.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_due.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_initiated.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_priority.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_state.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_type.sql
@@application/shared_components/user_interface/lovs/user_modules_db_pkgs.sql
@@application/shared_components/user_interface/lovs/users_userid.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/yes_no.sql
@@application/shared_components/user_interface/lovs/yes_no_2.sql
@@application/shared_components/user_interface/lovs/yes_no_3.sql
@@application/shared_components/user_interface/lovs/yes_no_4.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/report/chat_session_header.sql
@@application/shared_components/user_interface/templates/report/axa.sql
@@application/shared_components/user_interface/templates/report/chatcalls_region.sql
@@application/shared_components/user_interface/templates/report/chathistory_region.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/custom_authentication.sql
@@application/shared_components/plugins/item_type/ranrange_slider.sql
@@application/shared_components/plugins/item_type/slider.sql
@@application/shared_components/plugins/item_type/hr_bilog_mgoricki_advanced_slider.sql
@@application/shared_components/plugins/region_type/com_apexjsonviewer_plugin.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00014.sql
@@application/pages/page_00110.sql
@@application/pages/page_00114.sql
@@application/pages/page_00115.sql
@@application/pages/page_00116.sql
@@application/pages/page_00117.sql
@@application/pages/page_00118.sql
@@application/pages/page_00120.sql
@@application/pages/page_00121.sql
@@application/pages/page_00150.sql
@@application/pages/page_00151.sql
@@application/pages/page_00300.sql
@@application/pages/page_00301.sql
@@application/pages/page_00350.sql
@@application/pages/page_00351.sql
@@application/pages/page_00400.sql
@@application/pages/page_00410.sql
@@application/pages/page_00411.sql
@@application/pages/page_00420.sql
@@application/pages/page_00422.sql
@@application/pages/page_00423.sql
@@application/pages/page_00424.sql
@@application/pages/page_00425.sql
@@application/pages/page_00426.sql
@@application/pages/page_00427.sql
@@application/pages/page_00428.sql
@@application/pages/page_00429.sql
@@application/pages/page_00440.sql
@@application/pages/page_00500.sql
@@application/pages/page_00600.sql
@@application/pages/page_00610.sql
@@application/pages/page_00611.sql
@@application/pages/page_00630.sql
@@application/pages/page_00631.sql
@@application/pages/page_00632.sql
@@application/pages/page_00635.sql
@@application/pages/page_00650.sql
@@application/pages/page_00655.sql
@@application/pages/page_00665.sql
@@application/pages/page_00666.sql
@@application/pages/page_00702.sql
@@application/pages/page_00703.sql
@@application/pages/page_00704.sql
@@application/pages/page_00705.sql
@@application/pages/page_00708.sql
@@application/pages/page_00716.sql
@@application/pages/page_00717.sql
@@application/pages/page_00718.sql
@@application/pages/page_00720.sql
@@application/pages/page_00721.sql
@@application/pages/page_00722.sql
@@application/pages/page_01000.sql
@@application/pages/page_01001.sql
@@application/pages/page_01010.sql
@@application/pages/page_01011.sql
@@application/pages/page_01020.sql
@@application/pages/page_01021.sql
@@application/pages/page_01030.sql
@@application/pages/page_01031.sql
@@application/pages/page_01033.sql
@@application/pages/page_01034.sql
@@application/pages/page_01040.sql
@@application/pages/page_01041.sql
@@application/pages/page_01060.sql
@@application/pages/page_01061.sql
@@application/pages/page_01071.sql
@@application/pages/page_01080.sql
@@application/pages/page_01081.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
