--------------------------------------------------------
--  DDL for Sequence LKP_CONTEXT_DOMAIN_CATEGORIES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AI8P"."LKP_CONTEXT_DOMAIN_CATEGORIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
