prompt --application/pages/page_00014
begin
--   Manifest
--     PAGE: 00014
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>110979332345909267
,p_default_application_id=>119
,p_default_id_offset=>0
,p_default_owner=>'AI8P'
);
wwv_flow_imp_page.create_page(
 p_id=>14
,p_name=>'test'
,p_alias=>'TEST'
,p_step_title=>'test'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* ============================================================',
' * HELP SYSTEM LOGGER',
' * ============================================================ */',
'window.HELP_LOG = {',
unistr('  enabled: true,        // \D83D\DD34 set false in PROD'),
'  level: ''DEBUG'',       // DEBUG | INFO | WARN | ERROR',
'',
'  log(level, msg, data) {',
'    if (!this.enabled) return;',
'',
'    const levels = { DEBUG: 1, INFO: 2, WARN: 3, ERROR: 4 };',
'    if (levels[level] < levels[this.level]) return;',
'',
'    const time = new Date().toISOString().substring(11, 23);',
'    const prefix = `%c[HELP ${level}] ${time}`;',
'',
'    const style = {',
'      DEBUG: ''color:#64748b'',',
'      INFO:  ''color:#2563eb'',',
'      WARN:  ''color:#d97706'',',
'      ERROR: ''color:#dc2626;font-weight:bold''',
'    }[level];',
'',
'    console.log(prefix, style, msg, data ?? '''');',
'  },',
'',
'  debug(msg, d) { this.log(''DEBUG'', msg, d); },',
'  info(msg, d)  { this.log(''INFO'',  msg, d); },',
'  warn(msg, d)  { this.log(''WARN'',  msg, d); },',
'  error(msg, d) { this.log(''ERROR'', msg, d); }',
'};'))
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'(function () {',
'',
'  let hoverEnabled = true;',
'  let lastHoverItem = null;',
'',
'  window.userHasTechHelp = window.userHasTechHelp ?? false;',
'',
'  HELP_LOG.info(''Bootstrapping Help System'');',
'',
'  apex.util.invokeAfterPaint(initHelpSystem);',
'',
'  function initHelpSystem() {',
'',
'    HELP_LOG.debug(''invokeAfterPaint fired'');',
'',
'    const trigger  = document.getElementById(''helpTrigger'');',
'    const menu     = document.getElementById(''helpMenu'');',
'    const sidebar  = document.getElementById(''helpSidebar'');',
'    const overlay  = document.getElementById(''helpOverlay'');',
'    const closeBtn = document.getElementById(''closeHelp'');',
'    const content  = document.getElementById(''helpContent'');',
'',
'    if (!trigger || !menu || !sidebar || !overlay || !content) {',
'      HELP_LOG.error(''Missing required DOM elements'', {',
'        trigger, menu, sidebar, overlay, content',
'      });',
'      return;',
'    }',
'',
'    if (trigger.dataset.init === ''Y'') {',
unistr('      HELP_LOG.warn(''Help system already initialized \2014 skipping'');'),
'      return;',
'    }',
'',
'    trigger.dataset.init = ''Y'';',
'    HELP_LOG.info(''Help system initialized'');',
'',
'    /* ================================',
unistr('     * FAB \2192 MENU'),
'     * ================================ */',
'    trigger.addEventListener(''click'', function (e) {',
'      e.stopPropagation();',
'      const open = menu.style.display === ''block'';',
'      menu.style.display = open ? ''none'' : ''block'';',
'      HELP_LOG.debug(''FAB clicked'', { menuOpen: !open });',
'    });',
'',
'    document.addEventListener(''click'', function () {',
'      if (menu.style.display === ''block'') {',
'        menu.style.display = ''none'';',
'        HELP_LOG.debug(''Menu closed by document click'');',
'      }',
'    });',
'',
'    if (!window.userHasTechHelp) {',
'      menu.querySelectorAll(''.tech-only'').forEach(el => el.remove());',
'      HELP_LOG.info(''TECH help hidden (role not allowed)'');',
'    }',
'',
'    menu.addEventListener(''click'', function (e) {',
'      const mode = e.target.dataset.helpMode;',
'',
'      if (mode) {',
'        HELP_LOG.info(''Help mode selected'', mode);',
'        openHelp({ mode });',
'      }',
'',
'      if (e.target.id === ''toggleHoverHelp'') {',
'        hoverEnabled = !hoverEnabled;',
'        HELP_LOG.info(''Hover help toggled'', hoverEnabled);',
'        apex.message.showPageSuccess(',
'          hoverEnabled ? ''Hover help enabled'' : ''Hover help disabled''',
'        );',
'      }',
'',
'      menu.style.display = ''none'';',
'      e.stopPropagation();',
'    });',
'',
'    /* ================================',
'     * SIDEBAR',
'     * ================================ */',
'    function openHelp({ mode = ''USER'' } = {}) {',
'      HELP_LOG.info(''Opening help sidebar'', mode);',
'      sidebar.classList.add(''active'');',
'      overlay.classList.add(''active'');',
'      document.body.style.overflow = ''hidden'';',
'      loadHelpContent(mode);',
'    }',
'',
'    function closeHelp() {',
'      HELP_LOG.info(''Closing help sidebar'');',
'      sidebar.classList.remove(''active'');',
'      overlay.classList.remove(''active'');',
'      document.body.style.overflow = '''';',
'    }',
'',
'    closeBtn?.addEventListener(''click'', closeHelp);',
'    overlay.addEventListener(''click'', closeHelp);',
'',
'    window.openHelp  = openHelp;',
'    window.closeHelp = closeHelp;',
'',
'    /* ================================',
'     * AJAX CONTENT LOAD',
'     * ================================ */',
'    function loadHelpContent(mode) {',
'      const pageId = $v(''pFlowStepId'');',
'      HELP_LOG.debug(''Loading help content'', { pageId, mode });',
'',
'      content.innerHTML = `',
'        <div class="help-loading">',
'          <i class="fa fa-spinner fa-spin fa-2x"></i>',
unistr('          <p>Loading help\2026</p>'),
'        </div>',
'      `;',
'',
'      apex.server.process(',
'        ''GET_PAGE_HELP'',',
'        { x01: pageId, x02: mode },',
'        {',
'          success: function (data) {',
'            HELP_LOG.debug(''Help AJAX success'', data);',
'            content.innerHTML = data?.success',
'              ? data.html_content',
'              : getDefaultHelp(pageId);',
'          },',
'          error: function (err) {',
'            HELP_LOG.error(''Help AJAX failed'', err);',
'            content.innerHTML = getDefaultHelp(pageId);',
'          }',
'        }',
'      );',
'    }',
'',
'    function getDefaultHelp(pageId) {',
'      HELP_LOG.warn(''Using default help content'', pageId);',
'      return `',
'        <h3>Page ${pageId} Help</h3>',
'        <p>This page is currently being documented.</p>',
'      `;',
'    }',
'',
'    /* ================================',
'     * KEYBOARD',
'     * ================================ */',
'    document.addEventListener(''keydown'', function (e) {',
'',
'      if (e.key === ''F1'') {',
'        HELP_LOG.debug(''F1 pressed'');',
'        e.preventDefault();',
'        openHelp({ mode: ''USER'' });',
'      }',
'',
'      if (e.ctrlKey && e.key.toLowerCase() === ''h'' && window.userHasTechHelp) {',
'        HELP_LOG.debug(''CTRL+H pressed'');',
'        e.preventDefault();',
'        openHelp({ mode: ''TECH'' });',
'      }',
'',
'      if (e.key === ''Escape'' && sidebar.classList.contains(''active'')) {',
'        HELP_LOG.debug(''ESC pressed'');',
'        closeHelp();',
'      }',
'    });',
'',
'    /* ================================',
'     * HOVER HELP',
'     * ================================ */',
'    document.addEventListener(''mouseover'', function (e) {',
'      if (!hoverEnabled) return;',
'',
'      const item = e.target.closest(''[id^="P"]'');',
'      if (!item || item === lastHoverItem) return;',
'',
'      lastHoverItem = item;',
'',
'      HELP_LOG.debug(''Hover help requested'', item.id);',
'',
'      window.showHoverHelp?.({',
'        pageId: $v(''pFlowStepId''),',
'        itemName: item.id',
'      });',
'    });',
'',
'    HELP_LOG.info(''Help System READY'');',
'  }',
'',
'})();'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* Floating Help Button (SINGLE SOURCE OF TRUTH) */',
'.help-fab {',
'    position: fixed;',
'    bottom: 24px;',
'    right: 24px;',
'    width: 56px;',
'    height: 56px;',
'',
'    background: linear-gradient(135deg, #667eea, #764ba2);',
'    color: #fff;',
'',
'    border: none;',
'    border-radius: 50%;',
'    cursor: pointer;',
'',
'    display: flex;',
'    align-items: center;',
'    justify-content: center;',
'',
'    font-size: 20px;',
'    z-index: 100000;',
'',
'    /* NO transitions here */',
'    opacity: 1;',
'    visibility: visible;',
'    pointer-events: auto;',
'}',
'',
unistr('/* Hidden state \2013 JS ONLY */'),
'.help-fab.is-hidden {',
'    opacity: 0;',
'    visibility: hidden;',
'    pointer-events: none;',
'}',
'.help-fab-container {',
'    position: fixed;',
'    bottom: 24px;',
'    right: 24px;',
'    z-index: 100000;',
'}',
'',
'.help-menu {',
'    position: absolute;',
'    bottom: 64px;',
'    right: 0;',
'',
'    background: #fff;',
'    border-radius: 8px;',
'    box-shadow: 0 8px 24px rgba(0,0,0,.15);',
'    display: none;',
'    overflow: hidden;',
'    min-width: 180px;',
'}',
'',
'.help-menu button {',
'    width: 100%;',
'    padding: 10px 14px;',
'    background: none;',
'    border: none;',
'    text-align: left;',
'    cursor: pointer;',
'}',
'',
'.help-menu button:hover {',
'    background: #f3f4f6;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(161679535171437935)
,p_plug_name=>'helpPanel'
,p_region_name=>'helpPanel'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>10
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div id="helpSidebar" class="help-sidebar">',
'    <div class="help-sidebar-header">',
'        <h2>',
'            <i class="fa fa-question-circle"></i>',
'            Page Help',
'        </h2>',
'        <button id="closeHelp" class="help-close-btn">',
'            <i class="fa fa-times"></i>',
'        </button>',
'    </div>',
'    ',
'    <div class="help-sidebar-content" id="helpContent">',
'        <!-- Dynamic content will be loaded here -->',
'        <div class="help-loading">',
'            <i class="fa fa-spinner fa-spin fa-2x"></i>',
'            <p>Loading help...</p>',
'        </div>',
'    </div>',
'    ',
'    <div class="help-sidebar-footer">',
'        <a href="mailto:support@company.com?subject=Help Request - Page &APP_PAGE_ID." class="help-contact-link">',
'            <i class="fa fa-envelope"></i> Contact Support',
'        </a>',
'        <a href="f?p=&APP_ID.:9999:&SESSION.::&DEBUG.:::" class="help-docs-link">',
'            <i class="fa fa-book"></i> Full Documentation',
'        </a>',
'    </div>',
'</div>',
'',
'<div id="helpOverlay" class="help-overlay"></div>',
'',
'<!-- Floating Help Button -->',
'<button id="helpTrigger" class="help-fab" title="Page Help">',
'    <i class="fa fa-question-circle"></i>',
'</button>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(161680136639437941)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>20
,p_plug_display_point=>'REGION_POSITION_04'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="help-fab-container">',
'',
'  <button id="helpTrigger" class="help-fab" title="Help (F1)">',
'    <i class="fa fa-question-circle"></i>',
'  </button>',
'',
'  <div id="helpMenu" class="help-menu">',
unistr('    <button data-help-mode="USER">\D83D\DC64 User Help</button>'),
unistr('    <button data-help-mode="TECH" class="tech-only">\D83D\DEE0 Technical Help</button>'),
unistr('    <button id="toggleHoverHelp">\D83D\DEC8 Toggle Hover Help</button>'),
'  </div>',
'',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(162216223443776694)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(123954626239486075)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(161679680308437936)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_PAGE_HELP'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_page_id     NUMBER := apex_application.g_x01;',
'    v_help_html   CLOB;',
'BEGIN',
'    -- Get help content from help table',
'    BEGIN',
'        SELECT help_content',
'        INTO v_help_html',
'        FROM apex_page_help',
'        WHERE application_id = :APP_ID',
'          AND page_id = v_page_id',
'          AND is_active = ''Y'';',
'    EXCEPTION',
'        WHEN NO_DATA_FOUND THEN',
'            -- Generate default help based on page',
'          --  v_help_html := generate_default_help(v_page_id);',
'          Null;',
'    END;',
'    ',
'    -- Return JSON',
'    apex_json.open_object;',
'    apex_json.write(''success'', TRUE);',
'    apex_json.write(''html_content'', v_help_html);',
'    apex_json.close_object;',
'EXCEPTION',
'    WHEN OTHERS THEN',
'        apex_json.open_object;',
'        apex_json.write(''success'', FALSE);',
'        apex_json.write(''error'', SQLERRM);',
'        apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>161679680308437936
);
wwv_flow_imp.component_end;
end;
/
