--------------------------------------------------------
--  Ref Constraints for Table CFG_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "CFG_PARAMETERS" ADD FOREIGN KEY ("CATEGORY_CODE")
	  REFERENCES "LKP_PARAM_CATEGORY" ("CATEGORY_CODE") ENABLE;
  ALTER TABLE "CFG_PARAMETERS" ADD FOREIGN KEY ("VALUE_TYPE")
	  REFERENCES "LKP_PARAM_VALUE_TYPE" ("VALUE_TYPE") ENABLE;
  ALTER TABLE "CFG_PARAMETERS" ADD FOREIGN KEY ("PARAM_SCOPE")
	  REFERENCES "LKP_PARAM_SCOPE_TYPE" ("SCOPE_TYPE") ENABLE;
  ALTER TABLE "CFG_PARAMETERS" ADD CONSTRAINT "CFG_PARAMETERS_FK1_TENANT_ID" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "TENANTS" ("TENANT_ID") ENABLE;
