--------------------------------------------------------
--  Ref Constraints for Table CHAT_CALL_REGENERATIONS
--------------------------------------------------------

  ALTER TABLE "AI8P"."CHAT_CALL_REGENERATIONS" ADD CONSTRAINT "FK_REGEN_PARENT" FOREIGN KEY ("PARENT_CHAT_CALL_ID")
	  REFERENCES "AI8P"."CHAT_CALLS" ("CALL_ID") ENABLE;
  ALTER TABLE "AI8P"."CHAT_CALL_REGENERATIONS" ADD CONSTRAINT "FK_REGEN_CHILD" FOREIGN KEY ("CHILD_CHAT_CALL_ID")
	  REFERENCES "AI8P"."CHAT_CALLS" ("CALL_ID") ENABLE;
