--------------------------------------------------------
--  Ref Constraints for Table CONTEXT_DOMAIN_REGISTRY
--------------------------------------------------------

  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_REGISTRY" ADD CONSTRAINT "FK_CDR_DOMAIN" FOREIGN KEY ("CONTEXT_DOMAIN_ID")
	  REFERENCES "AI8P"."CONTEXT_DOMAINS" ("CONTEXT_DOMAIN_ID") ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_REGISTRY" ADD CONSTRAINT "FK_CDR_REGISTRY" FOREIGN KEY ("CONTEXT_REGISTRY_ID")
	  REFERENCES "AI8P"."CONTEXT_REGISTRY" ("CONTEXT_REGISTRY_ID") ENABLE;
