--------------------------------------------------------
--  Ref Constraints for Table CONTEXT_REGISTRY_ROLES
--------------------------------------------------------

  ALTER TABLE "AI8P"."CONTEXT_REGISTRY_ROLES" ADD CONSTRAINT "FK_CONTEXT_REGISTRY_ROLES" FOREIGN KEY ("CONTEXT_REGISTRY_ID")
	  REFERENCES "AI8P"."CONTEXT_REGISTRY" ("CONTEXT_REGISTRY_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_REGISTRY_ROLES" ADD CONSTRAINT "CONTEXT_REGISTRY_ROLES_FK1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "AI8P"."ROLES" ("ROLE_ID") ENABLE;
