--------------------------------------------------------
--  Ref Constraints for Table CONTEXT_REGISTRY
--------------------------------------------------------

  ALTER TABLE "CONTEXT_REGISTRY" ADD CONSTRAINT "CONTEXT_REGISTRY_FK2" FOREIGN KEY ("SENSITIVITY_LEVEL")
	  REFERENCES "LKP_REGISTRY_SENSITIVITY_LEVELS" ("SENSITIVITY_LEVEL") ENABLE;
  ALTER TABLE "CONTEXT_REGISTRY" ADD CONSTRAINT "RAG_SOURCE_REGISTRY_FK1" FOREIGN KEY ("REGISTRY_SOURCE_TYPE_CODE")
	  REFERENCES "LKP_CONTEXT_REGISTRY_SOURCE_TYPES" ("CONTEXT_REGISTRY_SOURCE_TYPE_CODE") ENABLE;
  ALTER TABLE "CONTEXT_REGISTRY" ADD CONSTRAINT "CONTEXT_REGISTRY_FK1" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCS" ("DOC_ID") ENABLE;
