--------------------------------------------------------
--  Ref Constraints for Table CONTEXT_REGISTRY_ROLES
--------------------------------------------------------

  ALTER TABLE "CONTEXT_REGISTRY_ROLES" ADD CONSTRAINT "FK_CONTEXT_REGISTRY_ROLES" FOREIGN KEY ("CONTEXT_REGISTRY_ID")
	  REFERENCES "CONTEXT_REGISTRY" ("CONTEXT_REGISTRY_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CONTEXT_REGISTRY_ROLES" ADD CONSTRAINT "CONTEXT_REGISTRY_ROLES_FK1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLES" ("ROLE_ID") ENABLE;
