--------------------------------------------------------
--  Ref Constraints for Table CONTEXT_DOMAIN_BEHAVIORS
--------------------------------------------------------

  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_BEHAVIORS" ADD CONSTRAINT "FK_MBF_MODE" FOREIGN KEY ("CONTEXT_DOMAIN_ID")
	  REFERENCES "AI8P"."CONTEXT_DOMAIN_INSTRUCTIONS" ("CONTEXT_DOMAIN_INSTRUCTION_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_BEHAVIORS" ADD CONSTRAINT "FK_MBF_BEHAVIOR" FOREIGN KEY ("DOMAIN_BEHAVIOR_CODE")
	  REFERENCES "AI8P"."LKP_CONTEXT_DOMAIN_BEHAVIORS" ("DOMAIN_BEHAVIOR_CODE") ENABLE;
  ALTER TABLE "AI8P"."CONTEXT_DOMAIN_BEHAVIORS" ADD CONSTRAINT "FK_MBF_FORMAT" FOREIGN KEY ("FORMAT_CODE")
	  REFERENCES "AI8P"."LKP_OUTPUT_FORMAT" ("FORMAT_CODE") ENABLE;
