--------------------------------------------------------
--  Ref Constraints for Table CONTEXT_DOMAINS
--------------------------------------------------------

  ALTER TABLE "CONTEXT_DOMAINS" ADD CONSTRAINT "FK_MODE_CATEGORY" FOREIGN KEY ("CONTEXT_DOMAIN_CATEGORY_ID")
	  REFERENCES "LKP_CONTEXT_DOMAIN_CATEGORIES" ("CONTEXT_DOMAIN_CATEGORY_ID") ENABLE;
  ALTER TABLE "CONTEXT_DOMAINS" ADD CONSTRAINT "CONTEXT_DOMAINS_FK1" FOREIGN KEY ("DETECTION_METHOD_CODE")
	  REFERENCES "LKP_DOMAIN_DETECTION_METHODS" ("DETECTION_METHOD_CODE") ENABLE;
  ALTER TABLE "CONTEXT_DOMAINS" ADD CONSTRAINT "CONTEXT_DOMAINS_FK2" FOREIGN KEY ("SCOPE_TYPE_CODE")
	  REFERENCES "LKP_CONTEXT_DOMAIN_SCOPE_TYPE" ("SCOPE_CODE") ENABLE;
