--------------------------------------------------------
--  Ref Constraints for Table DEBUG_AUDIT_LOG
--------------------------------------------------------

  ALTER TABLE "AI8P"."DEBUG_AUDIT_LOG" ADD CONSTRAINT "FK_DEBUG_AUDIT_TYPE" FOREIGN KEY ("AUDIT_EVENT_TYPE_CODE")
	  REFERENCES "AI8P"."LKP_DEBUG_AUDIT_EVENT_TYPES" ("AUDIT_EVENT_TYPE_CODE") ENABLE;
  ALTER TABLE "AI8P"."DEBUG_AUDIT_LOG" ADD CONSTRAINT "FK_DEBUG_AUDIT_EVENT_CODE" FOREIGN KEY ("EVENT_CODE")
	  REFERENCES "AI8P"."LKP_DEBUG_AUDIT_EVENTS" ("EVENT_CODE") ENABLE;
