--------------------------------------------------------
--  Ref Constraints for Table DEPLOYMENT_AUDIT_LOG
--------------------------------------------------------

  ALTER TABLE "AI8P"."DEPLOYMENT_AUDIT_LOG" ADD CONSTRAINT "FK_DEPLOY_AUDIT_DEPLOY" FOREIGN KEY ("DEPLOYMENT_ID")
	  REFERENCES "AI8P"."DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ENABLE;
  ALTER TABLE "AI8P"."DEPLOYMENT_AUDIT_LOG" ADD CONSTRAINT "FK_DEPLOY_AUDIT_USER" FOREIGN KEY ("TRIGGERED_BY_USER_ID")
	  REFERENCES "AI8P"."USERS" ("USER_ID") ENABLE;
