--------------------------------------------------------
--  Ref Constraints for Table DEPLOYMENT_AUDIT_LOG
--------------------------------------------------------

  ALTER TABLE "DEPLOYMENT_AUDIT_LOG" ADD CONSTRAINT "FK_DEPLOY_AUDIT_DEPLOY" FOREIGN KEY ("DEPLOYMENT_ID")
	  REFERENCES "DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ENABLE;
  ALTER TABLE "DEPLOYMENT_AUDIT_LOG" ADD CONSTRAINT "FK_DEPLOY_AUDIT_USER" FOREIGN KEY ("TRIGGERED_BY_USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
