--------------------------------------------------------
--  Ref Constraints for Table DEPLOYMENT_METRICS
--------------------------------------------------------

  ALTER TABLE "DEPLOYMENT_METRICS" ADD CONSTRAINT "FK_DEPLOY_METRICS_DEPLOY" FOREIGN KEY ("DEPLOYMENT_ID")
	  REFERENCES "DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ENABLE;
  ALTER TABLE "DEPLOYMENT_METRICS" ADD CONSTRAINT "FK_DEPLOY_METRICS_EXP" FOREIGN KEY ("EXPERIMENT_ID")
	  REFERENCES "DEPLOYMENT_EXPERIMENTS" ("EXPERIMENT_ID") ENABLE;
