--------------------------------------------------------
--  Ref Constraints for Table DEPLOYMENT_METRICS
--------------------------------------------------------

  ALTER TABLE "AI8P"."DEPLOYMENT_METRICS" ADD CONSTRAINT "FK_DEPLOY_METRICS_DEPLOY" FOREIGN KEY ("DEPLOYMENT_ID")
	  REFERENCES "AI8P"."DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ENABLE;
  ALTER TABLE "AI8P"."DEPLOYMENT_METRICS" ADD CONSTRAINT "FK_DEPLOY_METRICS_EXP" FOREIGN KEY ("EXPERIMENT_ID")
	  REFERENCES "AI8P"."DEPLOYMENT_EXPERIMENTS" ("EXPERIMENT_ID") ENABLE;
