--------------------------------------------------------
--  Ref Constraints for Table DOCS
--------------------------------------------------------

  ALTER TABLE "DOCS" ADD CONSTRAINT "FK_DOC_CHUNKING_STRATEGY" FOREIGN KEY ("CHUNKING_STRATEGY")
	  REFERENCES "LKP_CHUNKING_STRATEGY" ("STRATEGY_CODE") ENABLE;
  ALTER TABLE "DOCS" ADD CONSTRAINT "FK_CAT" FOREIGN KEY ("DOC_CATEGORY")
	  REFERENCES "LKP_DOC_CATEGORY" ("CATEGORY_CODE") ENABLE;
  ALTER TABLE "DOCS" ADD CONSTRAINT "FK_STATUS" FOREIGN KEY ("DOC_STATUS")
	  REFERENCES "LKP_DOC_STATUS" ("STATUS_CODE") ENABLE;
