--------------------------------------------------------
--  Ref Constraints for Table RAG_DOMAIN_SOURCES
--------------------------------------------------------

  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" ADD CONSTRAINT "FK_MODE_SOURCE_MODE" FOREIGN KEY ("CONTEXT_DOMAIN_ID")
	  REFERENCES "AI8P"."CONTEXT_DOMAINS" ("CONTEXT_DOMAIN_ID") ENABLE;
  ALTER TABLE "AI8P"."RAG_DOMAIN_SOURCES" ADD CONSTRAINT "FK_MODE_SOURCE_REGISTRY" FOREIGN KEY ("RAG_REGISTRY_ID")
	  REFERENCES "AI8P"."CONTEXT_REGISTRY" ("CONTEXT_REGISTRY_ID") ENABLE;
