--------------------------------------------------------
--  Ref Constraints for Table SHADOW_COMPARISON_LOG
--------------------------------------------------------

  ALTER TABLE "SHADOW_COMPARISON_LOG" ADD CONSTRAINT "SHADOW_COMP_LOG_SHADOW_FK" FOREIGN KEY ("SHADOW_DEPLOYMENT_ID")
	  REFERENCES "DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SHADOW_COMPARISON_LOG" ADD CONSTRAINT "SHADOW_COMP_LOG_PROD_FK" FOREIGN KEY ("PRODUCTION_DEPLOYMENT_ID")
	  REFERENCES "DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ON DELETE SET NULL ENABLE;
