--------------------------------------------------------
--  Ref Constraints for Table USER_SEGMENT_ASSIGNMENTS
--------------------------------------------------------

  ALTER TABLE "AI8P"."USER_SEGMENT_ASSIGNMENTS" ADD CONSTRAINT "FK_SEGMENT_ASSIGN_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "AI8P"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AI8P"."USER_SEGMENT_ASSIGNMENTS" ADD CONSTRAINT "FK_SEGMENT_ASSIGN_DEPLOY" FOREIGN KEY ("DEPLOYMENT_ID")
	  REFERENCES "AI8P"."DEPLOYMENT_VERSIONS" ("DEPLOYMENT_ID") ENABLE;
  ALTER TABLE "AI8P"."USER_SEGMENT_ASSIGNMENTS" ADD CONSTRAINT "FK_SEGMENT_ASSIGN_EXP" FOREIGN KEY ("EXPERIMENT_ID")
	  REFERENCES "AI8P"."DEPLOYMENT_EXPERIMENTS" ("EXPERIMENT_ID") ENABLE;
